### ISSUE TITLE
Editing bound EditText with android:textAllCaps causes exeption

### ISSUE THREAD

**Issue by tomcurran** [MvvmCross/MvvmCross#1002]
Created core & droid project, added mvvmcross, made a copy of the EditText in FirstView.axml with the additional attribute android:textAllCaps="true". Changing the value in the original EditText is ok but chaning the allCaps EditText causes exception. 

Using MvvmCross v3.5.1. Latest xamarin stable channel, xamarin studio 5.9, xamarin android v5.1.0.115.

```
[EGL_emulation] eglSurfaceAttrib not implemented
[SpannableStringBuilder] SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[SpannableStringBuilder] SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[EGL_emulation] eglSurfaceAttrib not implemented
[InputEventReceiver] Attempted to finish an input event but the input event receiver has already been disposed.
[EGL_emulation] eglSurfaceAttrib not implemented
[InputEventReceiver] Exception dispatching input event.
[MessageQueue-JNI] Exception in MessageQueue callback: handleReceiveCallback
[MessageQueue-JNI] java.lang.IndexOutOfBoundsException
[MessageQueue-JNI]  at android.graphics.Paint.getTextRunAdvances(Paint.java:1879)
[MessageQueue-JNI]  at android.text.TextLine.handleText(TextLine.java:747)
[MessageQueue-JNI]  at android.text.TextLine.handleRun(TextLine.java:898)
[MessageQueue-JNI]  at android.text.TextLine.measureRun(TextLine.java:414)
[MessageQueue-JNI]  at android.text.TextLine.measure(TextLine.java:293)
[MessageQueue-JNI]  at android.text.Layout.getHorizontal(Layout.java:852)
[MessageQueue-JNI]  at android.text.Layout.getHorizontal(Layout.java:830)
[MessageQueue-JNI]  at android.text.Layout.getPrimaryHorizontal(Layout.java:805)
[MessageQueue-JNI]  at android.text.Layout.getPrimaryHorizontal(Layout.java:795)
[MessageQueue-JNI]  at android.widget.Editor$HandleView.positionAtCursorOffset(Editor.java:3172)
[MessageQueue-JNI]  at android.widget.Editor$HandleView.show(Editor.java:3090)
[MessageQueue-JNI]  at android.widget.Editor$InsertionHandleView.show(Editor.java:3303)
[MessageQueue-JNI]  at android.widget.Editor$InsertionPointCursorController.show(Editor.java:3530)
[MessageQueue-JNI]  at android.widget.Editor$SuggestionsPopupWindow$CustomPopupWindow.dismiss(Editor.java:2339)
[MessageQueue-JNI]  at android.widget.Editor$PinnedPopupWindow.hide(Editor.java:2290)
[MessageQueue-JNI]  at android.widget.Editor$SuggestionsPopupWindow.hide(Editor.java:2537)
[MessageQueue-JNI]  at android.widget.Editor.hideCursorControllers(Editor.java:490)
[MessageQueue-JNI]  at android.widget.Editor.hideControllers(Editor.java:477)
[MessageQueue-JNI]  at android.widget.Editor.onTouchUpEvent(Editor.java:1604)
[MessageQueue-JNI]  at android.widget.TextView.onTouchEvent(TextView.java:7739)
[MessageQueue-JNI]  at android.view.View.dispatchTouchEvent(View.java:7706)
[MessageQueue-JNI]  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
[MessageQueue-JNI]  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
[MessageQueue-JNI]  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
[MessageQueue-JNI]  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
[MessageQueue-JNI]  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
[MessageQueue-JNI]  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
[MessageQueue-JNI]  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
[MessageQueue-JNI]  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
[MessageQueue-JNI]  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
[MessageQueue-JNI]  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
[MessageQueue-JNI]  at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
[MessageQueue-JNI]  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
[MessageQueue-JNI]  at android.view.View.dispatchPointerEvent(View.java:7886)
[MessageQueue-JNI]  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
[MessageQueue-JNI]  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
[MessageQueue-JNI]  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
[MessageQueue-JNI]  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
[MessageQueue-JNI]  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
[MessageQueue-JNI]  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
[MessageQueue-JNI]  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
[MessageQueue-JNI]  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
[MessageQueue-JNI]  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
[MessageQueue-JNI]  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
[MessageQueue-JNI]  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
[MessageQueue-JNI]  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
[MessageQueue-JNI]  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
[MessageQueue-JNI]  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
[MessageQueue-JNI]  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
[MessageQueue-JNI]  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
[MessageQueue-JNI]  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
[MessageQueue-JNI]  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
[MessageQueue-JNI]  at android.os.MessageQueue.nativePollOnce(Native Method)
[MessageQueue-JNI]  at android.os.MessageQueue.next(MessageQueue.java:138)
[MessageQueue-JNI]  at android.os.Looper.loop(Looper.java:123)
[MessageQueue-JNI]  at android.app.ActivityThread.main(ActivityThread.java:5017)
[MessageQueue-JNI]  at java.lang.reflect.Method.invokeNative(Native Method)
[MessageQueue-JNI]  
[AndroidRuntime] Shutting down VM
```

**Comment by slodge** [comment]
I'd guess you're feeding this with lowercase text through data-binding? If you do this, then I'd rather Mvx didn't cause a crash... but I'm not sure what it should do...

**Comment by tomcurran** [comment]
Tested and the case of the text being bound doesn't seem to effect the issue being seen. Editing the bound value through another EditText is possible with no issues seen. In this case the EditText with textAllCaps displays the value in all uppercase. Layout used below.

The issues only occur when changing values in the EditText with textAllCaps. I'm also not sure exactly what it should do but we definitely want to avoid the crash.

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:local="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">
    <EditText
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:textSize="40dp"
        local:MvxBind="Text Hello" />
    <EditText
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:textSize="40dp"
        android:textAllCaps="true"
        local:MvxBind="Text Hello" />
    <TextView
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:textSize="40dp"
        local:MvxBind="Text Hello" />
</LinearLayout>
```

**Comment by slodge** [comment]
OK - well there goes my first guess then :)

> Using MvvmCross v3.5.1. Latest xamarin stable channel, xamarin studio 5.9, xamarin android v5.1.0.115.

Wondering if this is a regression you've just seen in one of your apps or if it's something that has gone bang in some new code you are writing.

Do you know if this is a new issue since one ore more of the above changed? Is it just on Android 5.1? Just since Mvx 3.5.1? Or just since Xam 5.9? Or has it been around for a long time on multiple versions?

**Comment by tomcurran** [comment]
Same results tested with xamarin studio v5.7.2, xamarin android v4.20.0.28, mvvmcross 3.2.2 & 3.1.1

**Comment by castroAIG** [comment]
Have tried replacing the android:textAllCaps="true" on the EditText and use use android:inputType="textCapCharacters" ?

**Comment by filipercampos** [comment]
Replacing the android:textAllCaps="true" by android:inputType="textCapCharacters" worked for me !

**Comment by pragneshghoda** [comment]
I found the solution from this blog. Please check.
https://androidacademic.blogspot.com/2018/05/indexoutofbounds-exception-while-using.html
