### ISSUE TITLE
mvvcross4.0-beta5: Binary XML file line #1: Error inflating class Mvx.MvxListView

### ISSUE THREAD

**Issue by descorp** [MvvmCross/MvvmCross#1187]
After updating my android project up to mvvmcross 4.0-beta5 I'm getting this error:

```C#
android.view.InflateException: Binary XML file line #1: Error inflating class Mvx.MvxListView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
	...
Caused by: java.lang.ClassNotFoundException: Didn't find class \"Mvx.MvxListView\" on path: DexPathList[[zip file \"/data/app/com.timebook.android-1/base.apk\"],nativeLibraryDirectories=[/data/app/com.timebook.android-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.view.LayoutInflater.createView(LayoutInflater.java:571)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	... 28 more
	Suppressed: java.lang.ClassNotFoundException: Mvx.MvxListView
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 31 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

I've replace all tags in layouts to **cirrious.mvvmcross.binding.droid.views.MvxListView** : App does no crashes but seems ALL binding doesn't work. 

JIC, I restore all nuggets few times. 

Xamarin Studio
Version 5.10 (build 871)
Installation UUID: 42299ff2-9082-434a-9f11-93144d7bff46
Runtime:
	Mono 4.2.1 (explicit/6dd2d0d)
	GTK+ 2.24.23 (Raleigh theme)
	Package version: 402010102

Xamarin.Android
Version: 6.0.0.34 (Indie Edition)

SDK Tools Version: 24.4.1
SDK Platform Tools Version: 23.0.1
SDK Build Tools Version: 23.0.2

Java SDK: /usr
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

**Comment by martijn00** [comment]
What is your activity type? This was fixed in https://github.com/MvvmCross/MvvmCross/pull/1064

**Comment by descorp** [comment]
in my case it's a fragment initiated on **android/support/v7/app/ActionBarActivity**
What type should it be ?

It seams to my I should redesign app for *MvvmCross/MvvmCross-AndroidSupport* ?

**Comment by martijn00** [comment]
MvvmCross-AndroidSupport is the way to go. ActionBarActivity is deprecated and replaced with MvxAppCompatActivity.

**Comment by descorp** [comment]
Thanks @martijn00 , inheriting *MvxAppCompatActivity* seems like a solution
