### ISSUE TITLE
MvXListView giving error 

### ISSUE THREAD

**Issue by AmandaUrsula** [MvvmCross/MvvmCross#1234]
Hi

Can you please advise?

Since upgrading to 4.0.0, I this error when using a MvXListView in a layout:

```
java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at mono.android.SessionProjectCallback.instantiateClass(SessionProjectCallback.java:185)
	at mono.android.SessionProjectCallback.loadView(SessionProjectCallback.java:67)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:247)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:171)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:835)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:838)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:223)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:426)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at mono.android.DesignerSession.load(DesignerSession.java:170)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:640)
	at mono.android.MessageListener.executeMessage(MessageListener.java:87)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:745)
mono.android.DesignerException
	at mono.android.DesignerSession.load(DesignerSession.java:186)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:640)
	at mono.android.MessageListener.executeMessage(MessageListener.java:87)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:745)
```

Also, at runtime, nothing is rendered even though no errors are thrown.

The layout looks as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:local="http://schemas.android.com/apk/res-auto"
    style="@style/layout_vertical"
    android:background="@color/light">
    <FrameLayout
        android:id="@+id/scrollview"
        android:listSelector="@color/clear"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingBottom="@dimen/list_vertical_margin">
        <MvvmCross.Binding.Droid.Views.MvxListView
            android:id="@+id/SelectionsListView"
            android:listSelector="@color/clear"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            local:MvxBind="ItemsSource SelectionOptions;ItemClick ItemSelectedCommand;"
            local:MvxItemTemplate="@layout/selection_list_item" />
      <ProgressBar
            android:id="@+id/selectionsListProgess"
            style="?android:attr/progressBarStyle"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            local:MvxBind="Visibility Visibility(IsLoading)"
            android:layout_alignParentLeft="true"
            android:layout_alignParentTop="true"
            android:layout_below="@id/SelectionsListView" />
    </FrameLayout>
</LinearLayout>
```

Regards

Amanda

**Comment by Cheesebaron** [comment]
This is in the Xamarin Android designer or where?

**Comment by AmandaUrsula** [comment]
Hi, thanks for the reply.

Yes, El Capitan 10.11.3, Xamarin Studio , 5.10.2(build65), Xamarin Android 6.0.1.10, sdk  max = 6 (API level 23), min = 2.3 (API level 10).

Also,the bindings for ItemsSource do not fire

**Comment by martijn00** [comment]
Can you try to remove all packages and references to MvvmCross and install them again? It seems to me those are screwed up a bit.

**Comment by AmandaUrsula** [comment]
Hi

I did do that (except for the plugins ) But I will do it again just in case. Confirming that all bindings are not working, not just the MvxListView

**Comment by AmandaUrsula** [comment]
Hi, I did the following, none of the bindings are working:

- Removed my local repository. Restored to the last version which is on MvvmCross 3.5.1. The Android bindings are working fine. (i.e. prior to upgrading to 4.0.0)
- I upgraded my MvvmCross to 4.0.0
- None of the bindings are firing
- iOS, which is in the same solution, which obviously was also upgraded to MvvmCross 4.0.0, using the same Core project (PCL 4.5 - Profile78), is working perfectly

I made a sample project , using the MvvmCross.Droid.Support packages, and I am experiencing the same problem - bindings are not firing. Please see the SettingsViewModel,  and the fragment_settings.xml, which now has a MvxListView, in my sample project. Please read the comment in the Init method of the SettingsViewModel.

[MvvmCross-MvxListView.zip](https://github.com/MvvmCross/MvvmCross/files/124679/MvvmCross-MvxListView.zip)

**Comment by Cheesebaron** [comment]
You are adding items to a non observable `List` and doing it on a non-UI thread.

**Comment by martijn00** [comment]
Exactly what @Cheesebaron says. And please don't include zip files with your sample, but host it in some repo on GitHub.

**Comment by AmandaUrsula** [comment]
Thanks
