### ISSUE TITLE
MvxCachingFragmentActivity crash when minimizing with MVVMCross 4.1.0

### ISSUE THREAD

**Issue by Noires** [MvvmCross/MvvmCross#1273]
I have an issue since the last update (4.1.0) with the MvxCachingFragmentActivity and the new added AddToBackStack-Attribute. Each time i minimize my app it crashes and shows then the under actual behavior described error.

First i thought it was based on the Android SDK i was using, since it seemed like BaseBundle was added in API Level 21, but after changing to API Level 21, the error still occured. So iam kinda clueless at the moment. Atleast i can say for sure that it doesnt happen with 4.0.0 and the AddToBackStack works with the solution posted on stackoverflow [http://stackoverflow.com/a/36127871/1995301](url)

Maybe iam just doing something the way it is not intended, but atleast at the moment it seems the way that there may be an issue with the new update?

### Steps to reproduce
Since i cant really set up a project where iam atm, i will just give a rough description. Iam using MvxCachingFragmentActivity from Droid.Support.V7.Fragging with a FrameLayout for the Activity and then MvxFragment with `[MvxFragment(typeof(MainViewModel), Resource.Id.content_frame, true)]
`

### Expected behavior
App should just minimize.

### Actual behavior
App crashes after minimizing and shows the following error:

```
FATAL EXCEPTION: main
Process: MobileXcp.XcpAndroidApp, PID: 1855
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
	... 1 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.MissingMethodException: Method 'BaseBundle.PutBoolean' not found.
at MvvmCross.Droid.Support.V7.Fragging.Caching.MvxCachingFragmentActivity.OnSaveInstanceState (Android.OS.Bundle) <IL 0x00025, 0x0017b>
at Android.App.Activity.n_OnSaveInstanceState_Landroid_os_Bundle_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d419c934/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:4442
at (wrapper dynamic-method) object.5e871b6d-6297-4463-a9e7-fea5948b107a (intptr,intptr,intptr) <IL 0x00017, 0x00043>

	at md5904661e2cc60048b7a204cd0a4c4d7cc.MvxCachingFragmentActivity.n_onSaveInstanceState(Native Method)
	at md5904661e2cc60048b7a204cd0a4c4d7cc.MvxCachingFragmentActivity.onSaveInstanceState(MvxCachingFragmentActivity.java:39)
	at android.app.Activity.performSaveInstanceState(Activity.java:1383)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1286)
	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4475)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3847)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3910)
	at android.app.ActivityThread.access$1200(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5944)
	... 4 more
```

### Configuration

**Version:** 4.1.0

**Platform:** Android and Xamarin 3.11.590.0 (since the license expired)

**Plugins:** MvvmCross 4.1.0 + Requirements, MvvmCross Android Support V4 4.1.0 + Requirements

**Comment by Cheesebaron** [comment]
MvvmCross is built against latest stable Xamarin, we can't guarantee that it works with something that is many versions old.

It seems like there could be a signature mismatch between Bundle PutBoolean in the newer version compared to the new.

Will mark this as wontfix, until you rebuild your app against latest stable.
