### ISSUE TITLE
Snackbar Inflation Invalid Cast Exception

### ISSUE THREAD

**Issue by kellenlask** [MvvmCross/MvvmCross#1412]
### Repository 
https://github.com/kellenlask/SnackbarInflateErrorMvx

### Steps to reproduce

1. Create a view extending from MvxAppCompatActivity

2. In that view's layout, have a Support CoordinatorLayout

3. Make a Snackbar in the CoordinatorLayout. 

4. Snackbar usually works, but every now and again, you'll hit the inflation error. 

### StackTrace
`java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to android.widget.Button
	at android.support.design.widget.Snackbar$SnackbarLayout.onFinishInflate(Snackbar.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:826)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
	at md5bf0126c95bf9fc0db24c02c9adb4cfa7.MvxLayoutInflater.n_inflate(Native Method)
	at md5bf0126c95bf9fc0db24c02c9adb4cfa7.MvxLayoutInflater.inflate(MvxLayoutInflater.java:50)
	at android.support.design.widget.Snackbar.<init>(Snackbar.java:188)
	at android.support.design.widget.Snackbar.make(Snackbar.java:215)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6837)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Xamarin caused by: Java.Lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to android.widget.Button
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f9881b4b8 + 0x00028> in <filename unknown>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (JniObjectReference instance, JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) <0x7fac020088 + 0x000c7> in <filename unknown>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) <0x7fac01fe48 + 0x00193> in <filename unknown>:0 
  at Android.Views.LayoutInflater.Inflate (Int32 resource, Android.Views.ViewGroup root, Boolean attachToRoot) <0x7f980f5718 + 0x001a3> in <filename unknown>:0 
  at MvvmCross.Binding.Droid.Views.MvxLayoutInflater.Inflate (Int32 resource, Android.Views.ViewGroup root, Boolean attachToRoot) <0x7f980f2190 + 0x000eb> in <filename unknown>:0 
  at Android.Views.LayoutInflater.n_Inflate_ILandroid_view_ViewGroup_Z (IntPtr jnienv, IntPtr native__this, Int32 resource, IntPtr native_root, Boolean attachToRoot) <0x7f9889d158 + 0x00073> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:c804c682-4d9a-444b-91a8-6b63a8491f3d (intptr,intptr,int,intptr,bool)`

### Expected behavior
Correct Snackbar inflation 100% of the time.

### Actual behavior
Every now and again, MvxLayoutInflater tries to cast the snackbar's TextView as the snackbar's button.  

### Configuration

**Version:** 4.0.0

**Platform:** Android 5.1.1 -- Samsung SM-G920V, Asus Nexus 7

**Comment by kjeremy** [comment]
Try the latest MvvmCross.

**Comment by kjeremy** [comment]
This doesn't look like an MvvmCross bug.  It looks like a support library bug.  That said Xamarin STILL hasn't released the latest support libraries.

**Comment by martijn00** [comment]
@kellenlask Can you post your axml layout so we can review that?

@redth how's the update for the support libraries going?

**Comment by kellenlask** [comment]
I've updated, and haven't seen the issue yet. I'll close the issue if I still don't see it after a bit.

**Comment by minafaw** [comment]
I have the same issue , how can you fix it 

https://forums.xamarin.com/discussion/86554/snackbar-snackbarlayout-onfinishinflate-issue

http://stackoverflow.com/questions/41672636/snackbarsnackbarlayout-onfinishinflate-issue
