### ISSUE TITLE
Application crashing with invalid cast exception 

### ISSUE THREAD

**Issue by yalin78** [MvvmCross/MvvmCross#1678]
Hi,

Our production mobile android application is crashing with following exception. Any help is appreciated. 

android.runtime.JavaProxyThrowable
in alliantmobile.droid.activities.dashboard.DashboardActivity.n_onCreate

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
... 1 more
Caused by: android.runtime.JavaProxyThrowable: System.InvalidCastException: Specified cast is not valid.
at (wrapper castclass) System.Object:__castclass_with_cache (object,intptr,intptr)
at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatActivity`1[TViewModel].get_ViewModel () [0x00006] in <76c7f3cdfddd459898d814608e83832e>:0 
at AlliantMobile.Droid.Activities.AlliantActivity`1[TViewModel].OnCreate (Android.OS.Bundle bundle) [0x0004e] in <52edaf8934fc4e2e9e3a381b18c579c4>:0 
at AlliantMobile.Droid.Activities.Dashboard.DashboardActivity.OnCreate (Android.OS.Bundle bundle) [0x00000] in <52edaf8934fc4e2e9e3a381b18c579c4>:0 
at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <6296d3d76c5d4378959a1d9bf7205023>:0 
at (wrapper dynamic-method) System.Object:067f824e-d514-4111-ab8f-0c43823d975b (intptr,intptr,intptr)
at alliantmobile.droid.activities.dashboard.DashboardActivity.n_onCreate(Native Method)
at alliantmobile.droid.activities.dashboard.DashboardActivity.onCreate(DashboardActivity.java:34)
at android.app.Activity.performCreate(Activity.java:6285)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.access$900(ActivityThread.java:150)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:171)
at android.app.ActivityThread.main(ActivityThread.java:5417)
... 3 more

**Comment by Nickolas-** [comment]
Got the same error. It crashes randomly , right now trying to catch it.

**Comment by nmilcoff** [comment]
Might be the same issue as the described in #1305

**Comment by ornolisvt** [comment]
I have the same error, it happens randomly:

Fatal Exception: android.runtime.JavaProxyThrowable: System.InvalidCastException: Specified cast is not valid.
  at (wrapper castclass) System.Object:__castclass_with_cache (object,intptr,intptr)
  at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatActivity`1[TViewModel].get_ViewModel () [0x00006] in <60987d839dca4ba5beb932e22cb99ee3>:0 
  at PayPhone.Customer.Droid.Views.MainMenu.MainMenuView.SetupTabsWithViewPager () [0x00022] in <51dfc814b6fe44cea5a114b1b1ae00db>:0 
  at PayPhone.Customer.Droid.Views.MainMenu.MainMenuView.OnCreate (Android.OS.Bundle bundle) [0x00059] in <51dfc814b6fe44cea5a114b1b1ae00db>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <a55eaf0404344f868bb6954d029747d6>:0 
  at (wrapper dynamic-method) System.Object:fcec90cb-557e-4026-85d9-770b0440b64b (intptr,intptr,intptr)
       at md5440477be9fba792d21003e3e6e0bd3cb.MainMenuView.n_onCreate(MainMenuView.java)
       at md5440477be9fba792d21003e3e6e0bd3cb.MainMenuView.onCreate(MainMenuView.java:41)
       at android.app.Activity.performCreate(Activity.java:6155)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2600)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
       at android.app.ActivityThread.access$1200(ActivityThread.java:190)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5950)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

Fabric reported me five crashes on this devices:
Huawei Y5 II with Android 5.1
Galaxy S6 Edge with Android 7.0
LG Spree with Android 5.1.1 (I had never seen that mobile model)
Doogee X5 Max Pro with Android 6.0 (I had never seen that mobile model)

**Comment by Cheesebaron** [comment]
Create a repro sample and we will take a look.

So far we haven't been able to reproduce this at all. Nor do I own any of the mentioned devices.

**Comment by kjeremy** [comment]
Do you have a custom presenter?

**Comment by yalin78** [comment]
?This one got resolved.
________________________________

**Comment by Cheesebaron** [comment]
No this one was never reproduced.

**Comment by ornolisvt** [comment]
Yes I have a custom presenter @kjeremy 
    public class MvxCustomDroidPresenter : MvxAppCompatViewPresenter
    {
        public MvxCustomDroidPresenter(IEnumerable<Assembly> AndroidViewAssemblies) : base(AndroidViewAssemblies)
        {

        }

        public override void RegisterAttributeTypes()
        {
            base.RegisterAttributeTypes();
            AttributeTypesToActionsDictionary.Add(
                typeof(MvxCustomActivityPresentationAttribute),
                new MvxPresentationAttributeAction
                {
                    ShowAction = (view, attribute, request) => ShowActivity(view, (MvxCustomActivityPresentationAttribute)attribute, request),
                    CloseAction = (viewModel, attribute) => CloseActivity(viewModel, (MvxCustomActivityPresentationAttribute)attribute)
                });
        }


        protected override void ShowActivity(Type view, MvxActivityPresentationAttribute attribute, MvxViewModelRequest request)
        {
            var intent = CreateIntentForRequest(request);
            if (request != null && request.PresentationValues != null)
            {
                if (request.PresentationValues.ContainsKey("NavigationMode") && request.PresentationValues.ContainsKey("ClearTask"))
                    intent.SetFlags(ActivityFlags.ClearTop | ActivityFlags.NewTask | ActivityFlags.ClearTask);
                else
                if (request.PresentationValues.ContainsKey("NavigationMode"))
                    intent.SetFlags(ActivityFlags.ClearTop | ActivityFlags.NewTask);
            }
            if (attribute.Extras != null)
                intent.PutExtras(attribute.Extras);

            var activity = CurrentActivity;
            if (activity == null)
            {
                Mvx.Resolve<IMvxLog>().Warn("Cannot Resolve current top activity");
                return;
            }

            var activityOptions = CreateActivityTransitionOptions(intent, attribute);
            if (activityOptions != null)
            {
                activity.StartActivity(intent, activityOptions.ToBundle());
            }
            else
                activity.StartActivity(intent);
            if (attribute is MvxCustomActivityPresentationAttribute)
            {
                var att = (MvxCustomActivityPresentationAttribute)attribute;
                if (att.EnterAnimation.Equals(int.MinValue) && att.ExitAnimation.Equals(int.MinValue)) return;
                activity.OverridePendingTransition(att.EnterAnimation, att.ExitAnimation);
            }
        }
    }

**Comment by nickrandolph** [comment]
Any chance you can try to repro using the Playground samples? If you can, please submit as a PR referencing this issue and we’ll investigate further
