### ISSUE TITLE
Newtonsoft.Json.dll compilation problems

### ISSUE THREAD

**Issue by MihaMarkic** [MvvmCross/MvvmCross#187]
One more problem when compiling v3 samples - I am getting the error below. Any idea how to workaround? Perhaps using Newtonsoft.Json.dll sources?

Error   172 Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Newtonsoft.Json.dll'
   at Monodroid.Tuner.MonoDroidResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(List`1 assemblies, AssemblyDefinition assembly)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute() TestOne

**Comment by lvialle** [comment]
if you get this issue, uncheck "Local Copy" and Recheck it, it seems to be a bug with the default value. It should work at least withing Xamarin Studio
