### ISSUE TITLE
UWP After upgrading to MvvmCross 5.0.3 exception is thrown in MvxSuspensionManager.SaveAsync()

### ISSUE THREAD

**Issue by ryssel** [MvvmCross/MvvmCross#1970]
### Steps to reproduce

1. Open my app

2. Exit app so Suspending event is fired

### Expected behavior
In MvvmCross 5.0.2 and before it worked fine

### Actual behavior
ArgumentOutOfRangeException is fired

+		$exception	{MvvmCross.Uwp.Views.Suspension.MvxSuspensionManagerException: MvxSuspensionManager failed ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Runtime.InteropServices.WindowsRuntime.VectorToListAdapter.Indexer_Get[T](Int32 index)
   at MvvmCross.Uwp.Views.MvxWindowsPage.OnNavigatedFrom(NavigationEventArgs e)
   at Windows.UI.Xaml.Controls.Frame.GetNavigationState()
   at MvvmCross.Uwp.Views.MvxWrappedFrame.GetNavigationState()
   at MvvmCross.Uwp.Views.Suspension.MvxSuspensionManager.<SaveAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at MvvmCross.Uwp.Views.Suspension.MvxSuspensionManager.<SaveAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TrackMan.Soccer.UWP.App.<OnSuspending>d__17.MoveNext()}	MvvmCross.Uwp.Views.Suspension.MvxSuspensionManagerException

### Configuration

**Version:** 5.0.3

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] WPF
- [X] UWP

![image](https://user-images.githubusercontent.com/6928064/27326132-ef89fd04-55aa-11e7-98d1-316a59692255.png)

**Comment by Cheesebaron** [comment]
Can you work without the SuspensionManager for now?

For UWP and our PCL's you should be able to get symbols, by simply checking `Enable source server support` in Tools > Options > Debugging > General in VS.

**Comment by nmilcoff** [comment]
@nickrandolph did you maybe solve this issue on #2434?

**Comment by nickrandolph** [comment]
Yes I think the issue was because mvx was trying to persist info for the backstack that can be null/empty without checking
