### ISSUE TITLE
Crash attempting to select spinner to view items

### ISSUE THREAD

**Issue by sisterray** [MvvmCross/MvvmCross#2392]
### Steps to reproduce :scroll:

Attempting to touch spinner to view list crashes on v5.4.2 but works in v4.2.3. If this is not a bug, can someone explain what I am doing wrong.

**Definition of my spinner**

```
<MvxSpinner
                android:layout_width="match_parent"
                android:focusable="true"
                android:focusableInTouchMode="true"
                android:layout_height="34dp"
                android:textStyle="bold"
                android:id="@+id/myspinner"
                android:layout_marginLeft="16dp"
                android:layout_marginRight="16dp"
                local:MvxItemTemplate="@layout/spinner_item"
                android:textColor="@color/black"
                local:MvxBind="ItemsSource MyItems ;SelectedItem SelectedItem" />
```

**spinner_item layout**

```
<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:local="http://schemas.android.com/apk/res-auto"
          android:id="@+id/role"
    android:foreground="#ffffff"
    android:textColor="@color/black"
    android:gravity="center_vertical"
    android:paddingLeft="8dp"
    style="@android:style/TextAppearance.Medium"
    android:layout_width="match_parent"
    android:layout_height="34dp"
    local:MvxBind="Text Name" />
```

**I access the spinner like this**
`spinner = inflatedView.FindViewById<MvxAppCompatSpinner>(Resource.Id.myspinner);`

**The data item**

```
public class MyItem
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
```

### Expected behavior :thinking:
When I touch the spinner the items are shown. This works in MvvmCross v4.2.3 but not in V5.4.2
I have attempted the following to fix it

- Added MvxAppCompatSetupHelper.FillTargetFactories(registry); to the overridden Setup FillTargetFactories method

- Added an xml resource file called Empty.xml . This seems to generate the support_simple_spinner_dropdown_item resource layout id

- Changed my axml file to use mvvmcross.droid.support.v7.appcompat.widget.MvxAppCompatSpinner instead of MvxSpinner

I also noticed there was a change related to MvxAppCompatSpinner MvvmCross issue #1666. Does anyone know if the application code need to be changed because of this?

### Actual behavior :bug:
Get an exception
**No package identifier when getting value for resource number 0x00000000**

Stack Trace
```
UNHANDLED EXCEPTION:
Android.Content.Res.Resources+NotFoundException: Resource ID #0x0
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a8] in /Users/builder/data/lanes/3511/501e63ce/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11687 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0006b] in /Users/builder/data/lanes/3511/501e63ce/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:355 
  at Android.Views.LayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x00054] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Views.LayoutInflater.cs:653 
  at MvvmCross.Binding.Droid.Views.MvxLayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x0003e] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxLayoutInflater.cs:137 
  at MvvmCross.Binding.Droid.BindingContext.MvxAndroidBindingContext.CommonInflate (System.Int32 resourceId, Android.Views.ViewGroup viewGroup, System.Boolean attachToRoot) [0x00013] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\BindingContext\MvxAndroidBindingContext.cs:52 
  at MvvmCross.Binding.Droid.BindingContext.MvxAndroidBindingContext.BindingInflate (System.Int32 resourceId, Android.Views.ViewGroup viewGroup, System.Boolean attachToRoot) [0x00000] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\BindingContext\MvxAndroidBindingContext.cs:36 
  at MvvmCross.Binding.Droid.Views.MvxListItemView..ctor (Android.Content.Context context, MvvmCross.Binding.Droid.Views.IMvxLayoutInflaterHolder layoutInflaterHolder, System.Object dataContext, Android.Views.ViewGroup parent, System.Int32 templateId) [0x0001c] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxListItemView.cs:33 
  at MvvmCross.Binding.Droid.Views.MvxAdapter.CreateBindableView (System.Object dataContext, Android.Views.ViewGroup parent, System.Int32 templateId) [0x0002f] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxAdapter.cs:235 
  at MvvmCross.Binding.Droid.Views.MvxAdapter.GetBindableView (Android.Views.View convertView, System.Object dataContext, Android.Views.ViewGroup parent, System.Int32 templateId) [0x00025] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxAdapter.cs:212 
  at MvvmCross.Binding.Droid.Views.MvxAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent, System.Int32 templateId) [0x00022] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxAdapter.cs:196 
  at MvvmCross.Binding.Droid.Views.MvxAdapter.GetDropDownView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00000] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxAdapter.cs:181 
  at Android.Widget.BaseAdapter.n_GetDropDownView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x0001a] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Widget.BaseAdapter.cs:194 
  at (wrapper dynamic-method) System.Object:3ed74d6a-6db7-456d-93fd-5b367d4d6acb (intptr,intptr,int,intptr,intptr)
  --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---
android.content.res.Resources$NotFoundException: Resource ID #0x0
    at android.content.res.Resources.getValue(Resources.java:1130)
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2321)
    at android.content.res.Resources.getLayout(Resources.java:946)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
    at md5bae3d7ea3f28e5e7c6558943f4e84d30.MvxAdapter.n_getDropDownView(Native Method)
    at md5bae3d7ea3f28e5e7c6558943f4e84d30.MvxAdapter.getDropDownView(MvxAdapter.java:84)
    at android.support.v7.widget.AppCompatSpinner$DropDownAdapter.getDropDownView(AppCompatSpinner.java:641)
    at android.support.v7.widget.AppCompatSpinner$DropDownAdapter.getView(AppCompatSpinner.java:636)
    at android.support.v7.widget.AppCompatSpinner.compatMeasureContentWidth(AppCompatSpinner.java:562)
    at android.support.v7.widget.AppCompatSpinner$DropdownPopup.computeContentWidth(AppCompatSpinner.java:754)
    at android.support.v7.widget.AppCompatSpinner$DropdownPopup.show(AppCompatSpinner.java:779)
    at android.support.v7.widget.AppCompatSpinner.performClick(AppCompatSpinner.java:432)
    at android.view.View$PerformClick.run(View.java:18570)
    at android.os.Handler.handleCallback(Handler.java:743)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5196)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
    at dalvik.system.NativeStart.main(Native Method)
```

### Configuration :wrench:

**Version:** 5.4.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
It complains about not finding Resource with ID 0x0. Sounds like you need yo clean your project

**Comment by sisterray** [comment]
Hi, I've tried that multiple times and I'm still getting the same result

**Comment by sisterray** [comment]
@kjeremy Do you have any idea what I need to change to make this work as before? I'm only asking as I think you implemented issue #1666

**Comment by kjeremy** [comment]
@sisterray Did you actually delete your `bin` and `obj` directories?  Sometimes that is needed.  And removing the app from the phone just to be safe.

What happens if you remove `local:MvxItemTemplate="@layout/spinner_item"`?

If that doesn't work I would try overriding the resources the spinner is using (look at what you added in the axml and maybe try to override the ones I introduced in that PR) to something that you know exists.

**Comment by sisterray** [comment]
Hi @kjeremy ,

Thanks for getting back to me.

I did delete the bin and obj directories, but did not delete the app from the device. I'll check this when I'm back at work next week. I'll also try to remove the local:MvxItemTemplate, but how would this bind the spinner to my list of MyItem objects?

I'm not sure what you mean by overriding the resources the spinner is using. Can you clarify what you mean by this?

**Comment by Cheesebaron** [comment]
It will just use `ToString()` on the ViewModel you have in the `ItemsSource`

**Comment by EMarshal** [comment]
Seeing the same behavior in a project I'm working on. Was functional as late as 5.1.0, seems non-functional in 5.3.0. Clearing bin/obj and deleting the app and Mono library doesn't help.

No crash if the `ItemsSource` collection is empty (or if `ItemsSource` isn't bound), but crash immediately when loading view if `ItemsSource` has any items. I'm not setting `MvxItemTemplate`.

Similar-looking stack trace:

```
UNHANDLED EXCEPTION:
Android.Content.Res.Resources+NotFoundException: Resource ID #0x0
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <7cfbebb561c54efc9010b018c0846c7e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <7cfbebb561c54efc9010b018c0846c7e>:0 
  at Android.Views.LayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x0005a] in <9ef29c909d7e4606a46b131129da3975>:0 
  at MvvmCross.Binding.Droid.Views.MvxLayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x0003e] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxLayoutInflater.cs:137 
  at MvvmCross.Binding.Droid.BindingContext.MvxAndroidBindingContext.CommonInflate (System.Int32 resourceId, Android.Views.ViewGroup viewGroup, System.Boolean attachToRoot) [0x00013] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\BindingContext\MvxAndroidBindingContext.cs:52 
  at MvvmCross.Binding.Droid.BindingContext.MvxAndroidBindingContext.BindingInflate (System.Int32 resourceId, Android.Views.ViewGroup viewGroup, System.Boolean attachToRoot) [0x00000] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\BindingContext\MvxAndroidBindingContext.cs:36 
  at MvvmCross.Binding.Droid.Views.MvxListItemView..ctor (Android.Content.Context context, MvvmCross.Binding.Droid.Views.IMvxLayoutInflaterHolder layoutInflaterHolder, System.Object dataContext, Android.Views.ViewGroup parent, System.Int32 templateId) [0x0001c] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxListItemView.cs:33 
  at MvvmCross.Binding.Droid.Views.MvxAdapter.CreateBindableView (System.Object dataContext, Android.Views.ViewGroup parent, System.Int32 templateId) [0x0002f] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxAdapter.cs:235 
  at MvvmCross.Binding.Droid.Views.MvxAdapter.GetBindableView (Android.Views.View convertView, System.Object dataContext, Android.Views.ViewGroup parent, System.Int32 templateId) [0x00025] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxAdapter.cs:212 
  at MvvmCross.Binding.Droid.Views.MvxAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent, System.Int32 templateId) [0x00022] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxAdapter.cs:196 
  at MvvmCross.Binding.Droid.Views.MvxAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00000] in C:\projects\mvvmcross\MvvmCross\Binding\Droid\Views\MvxAdapter.cs:184 
  at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x00018] in <9ef29c909d7e4606a46b131129da3975>:0 
  at (wrapper dynamic-method) System.Object:c5ba7f45-1526-4b6c-bfc1-641595762d08 (intptr,intptr,int,intptr,intptr)
  --- End of managed Android.Content.Res.Resources+NotFoundException stack trace ---
android.content.res.Resources$NotFoundException: Resource ID #0x011-16 12:56:04.757 I/MonoDroid(14935): 	at android.content.res.Resources.getValue(Resources.java:1351)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2774)
	at android.content.res.Resources.getLayout(Resources.java:1165)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
	at md5bae3d7ea3f28e5e7c6558943f4e84d30.MvxAdapter.n_getView(Native Method)
	at md5bae3d7ea3f28e5e7c6558943f4e84d30.MvxAdapter.getView(MvxAdapter.java:92)
	at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:194)
	at android.widget.Spinner.onMeasure(Spinner.java:580)
	at android.support.v7.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:416)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1191)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by kjeremy** [comment]
If you create your `MvxAdapter` in your code does this still occur?

**Comment by EMarshal** [comment]
Yes, still crashes with `MvxAdapter` created in code.

**Comment by kjeremy** [comment]
Please link to an easily reproducible example.

**Comment by EMarshal** [comment]
I [forked MvvmCross-Samples](https://github.com/EMarshal/MvvmCross-Samples) and edited the StarWarsSample to use an `MvxSpinner` for the planets view. That causes a crash on launch.

**Comment by alexanderhanssen** [comment]
I ran into this problem a few weeks back, and i "fixed" it by using Mvx.MvxSpinner instead of MvxSpinner.

When using MvxItemTemplate and MvxDropDwnItemTemplate together, MvxSpinner works normally.
```
<MvxSpinner  
    android:layout_width="wrap_content"  
    android:layout_height="wrap_content"  
    local:MvxItemTemplate="@layout/spinner_item"  
    local:MvxDropDownItemTemplate="@layout/spinner_dropdown_item"  
    local:MvxBind="ItemsSource AllItems;SelectedItem SelectedItem;" />
```

When only using MvxItemTemplate, MvxSpinner crashes when clicking on the spinner (same exception as posted first).
```
<MvxSpinner
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    local:MvxItemTemplate="@layout/spinner_item"
    local:MvxBind="ItemsSource AllItems;SelectedItem SelectedItem;" />
```
Only using MvxItemTemplate does not crash when using Mvx.MvxSpinner
```
<Mvx.MvxSpinner
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    local:MvxItemTemplate="@layout/spinner_item"
    local:MvxBind="ItemsSource AllItems;SelectedItem SelectedItem;" />
```
When not using either, MvxSpinner crashes when showing the spinner (before being able to click)
```
<MvxSpinner
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    local:MvxBind="ItemsSource AllItems;SelectedItem SelectedItem;" />
```
This does not crash, but uses default templates
```
<Mvx.MvxSpinner
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    local:MvxBind="ItemsSource AllItems;SelectedItem SelectedItem;" />
```
Hopefully this might help locating the issue!

**Comment by sisterray** [comment]
Hi,

Is @layout/spinner_dropdown_item something you have written? I am getting an error

**Comment by alexanderhanssen** [comment]
Yea `@layout/spinner_dropdown_item` is something i have written. I'm currently on 5.2.1, i'll let you know once i have the time to update.
Maybe try changing this `spinner = inflatedView.FindViewById<MvxAppCompatSpinner>(Resource.Id.myspinner);` to this `spinner = inflatedView.FindViewById<MvxSpinner>(Resource.Id.myspinner);`

**Comment by Cheesebaron** [comment]
I think last last major change was that MvxListViewItem changed from being a wrapper view to being a ViewHolder, which I did in August released in 5.2.0. This prevents a bunch of layout issues that both ListView and Spinner had before. Also did a whole bunch of changes to MvxAdapter to accommodate for this.

I do see that `MvxAppCompatSpinner` looks a bit different from `MvxSpinner`, so there might be some inconsistencies between those two. The thing that catches my eyes is that in `MvxSpinner` in the ctor, I only assign template Ids from attributes if they are `> 0`. This looks different in `MvxAppCompatSpinner`.

This is probably the root issue and you should be able to prevent this by assigning both `MvxItemTemplate` and `MvxDropDownItemTemplate` when using the `MvxAppCompatSpinner`.

**Comment by sisterray** [comment]
Hi All

I did what @Cheesebaron suggested and it worked.

```
<MvxSpinner
                android:layout_width="match_parent"
                android:layout_height="34dp"
                android:id="@+id/rolespinner"
                local:MvxDropDownItemTemplate="@layout/item_spinnerdropdown"
                local:MvxItemTemplate="@layout/item_spinner" 
                local:MvxBind="ItemsSource Roles;SelectedItem SelectedRole" />
```

Could someone briefly explain the explain to me what the difference is between `local:MvxDropDownItemTemplate` and `local:MvxItemTemplate`

**Comment by Cheesebaron** [comment]
Reading the [Android documentation about Spinner](https://developer.android.com/guide/topics/ui/controls/spinner.html) the drop down resource is the layout shown for each item in the drop down when you press the spinner.

So `MvxItemTemplate` will be used for the first item always visible and `MvxDropDownItemTemplate` for the items in the drop down.

**Comment by sisterray** [comment]
Thanks @Cheesebaron
