### ISSUE TITLE
Sometimes open the app and then it crashes

### ISSUE THREAD

**Issue by haohighview** [MvvmCross/MvvmCross#2599]
### Steps to reproduce :scroll:

start the app and then it crashes

Xamarin caused by: android.runtime.JavaProxyThrowable: MvvmCross.Platform.Exceptions.MvxException: MvxTrace already initialized
  at MvvmCross.Platform.Platform.MvxTrace.Initialize () <0xce95db34 + 0x000ac> in <3a7f3a9829fa437eade9aec79c664fd4>:0 
  at MvvmCross.Core.Platform.MvxSetup.InitializeDebugServices () <0xcde61214 + 0x0003b> in <5db72be84c2049f2ba5806f126d0f185>:0 
  at MvvmCross.Core.Platform.MvxSetup.InitializePrimary () <0xcde60510 + 0x0010f> in <5db72be84c2049f2ba5806f126d0f185>:0 
  at MvvmCross.Droid.Platform.MvxAndroidSetupSingleton.InitializeFromSplashScreen (MvvmCross.Droid.Views.IMvxAndroidSplashScreenActivity splashScreen) <0xccf4d198 + 0x00173> in <603806df82224ab88e3e92f1d734fe50>:0 
  at MvvmCross.Droid.Views.MvxSplashScreenActivity.OnCreate (Android.OS.Bundle bundle) <0xccf53b4c + 0x0003f> in <603806df82224ab88e3e92f1d734fe50>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) <0xcf16b778 + 0x0006f> in <c06f3b67f8994ee29f98fb0873d39840>:0 
  at (wrapper dynamic-method) System.Object:f39e9bc4-44e6-4a9a-8423-4b3d9d65b6cf (intptr,intptr,intptr)
	at mvvmcross.droid.views.MvxSplashScreenActivity.n_onCreate(Native Method)
	at mvvmcross.droid.views.MvxSplashScreenActivity.onCreate(MvxSplashScreenActivity.java:31)
	at android.app.Activity.performCreate(Activity.java:6999)
	at android.app.Activity.performCreate(Activity.java:6990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

### Configuration :wrench:

**Version:**
vs2017 15.5.4
Xamarin 4.8.0.757
MvvmCross 5.5.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nickrandolph** [comment]
@haohighview do you see the same behaviour in the Playground sample?

**Comment by haohighview** [comment]
yes, I see. Do I need to update the version of the MvvmCross?

**Comment by nickrandolph** [comment]
Yes, please try 5.6.3 which I think is latest stable

**Comment by nmilcoff** [comment]
Can you please add your Android Setup class?

**Comment by haohighview** [comment]
[Setup-old.txt](https://github.com/MvvmCross/MvvmCross/files/1779907/Setup-old.txt)
[Setup-new.txt](https://github.com/MvvmCross/MvvmCross/files/1779908/Setup-new.txt)
I updated the "MvvmCross" version and changed "Setup" to "Setup-new".

**Comment by martijn00** [comment]
Trace is removed from MvvmCross 6.0.
