### ISSUE TITLE
Failed to navigate Frame to MvxWindowsPage

### ISSUE THREAD

**Issue by yogeshnataraj** [MvvmCross/MvvmCross#2971]
HI,
Trying to navigate native UWP user control **Frame** to **MvxWindowsPage**, there i am getting the arrangement null exception 

**Exception**
   at MvvmCross.Core.Parse.StringDictionary.MvxStringDictionaryParser.Parse(String textToParse) in D:\git\MvvmCross\MvvmCross\Core\Core\Parse\StringDictionary\MvxStringDictionaryParser.cs:line 23
   at MvvmCross.Core.Parse.StringDictionary.MvxViewModelRequestCustomTextSerializer.DeserializeObject(Type type, String inputText) in D:\git\MvvmCross\MvvmCross\Core\Core\Parse\StringDictionary\MvxViewModelRequestCustomTextSerializer.cs:line 53
   at MvvmCross.Core.Parse.StringDictionary.MvxViewModelRequestCustomTextSerializer.DeserializeObject[T](String inputText) in D:\git\MvvmCross\MvvmCross\Core\Core\Parse\StringDictionary\MvxViewModelRequestCustomTextSerializer.cs:line 33
   at MvvmCross.Uwp.Views.MvxWindowsViewsContainer.Load(String requestText, IMvxBundle savedState) in D:\git\MvvmCross\MvvmCross\Windows\Uwp\Views\MvxWindowsViewsContainer.cs:line 26
   at MvvmCross.Uwp.Views.MvxWindowsExtensionMethods.<>c__DisplayClass0_0.<OnViewCreate>b__0() in D:\git\MvvmCross\MvvmCross\Windows\Uwp\Views\MvxWindowsExtensionMethods.cs:line 22
   at MvvmCross.Uwp.Views.MvxWindowsExtensionMethods.OnViewCreate(IMvxWindowsView storeView, String requestText, Func`1 bundleLoader) in D:\git\MvvmCross\MvvmCross\Windows\Uwp\Views\MvxWindowsExtensionMethods.cs:line 22
   at MvvmCross.Uwp.Views.MvxWindowsPage.OnNavigatedTo(NavigationEventArgs e) in D:\git\MvvmCross\MvvmCross\Windows\Uwp\Views\MvxWindowsPage.cs:line 97
   at Windows.UI.Xaml.Controls.Page.global::Windows.UI.Xaml.Controls.IPageOverrides.OnNavigatedTo(NavigationEventArgs e) in C:\Users\yoheswarann\Documents\Projects\vipcs\ViewPoint.Win\ViewPoint\obj\x86\Release\ilc\intermediate\Viewpoint.PCMobile.Windows.McgInterop\SafeTypes.g.cs:line 32897
   at __Interop.ReverseComStubs.Stub_4[TArg0](Object __this, Void* unsafe_p, IntPtr __methodPtr) in C:\Users\yoheswarann\Documents\Projects\vipcs\ViewPoint.Win\ViewPoint\obj\x86\Release\ilc\intermediate\Viewpoint.PCMobile.Windows.McgInterop\SharedStubs.g.cs:line 9341

**Button click** 
`var settingsRequest = new MvvmCross.Core.ViewModels.MvxViewModelRequest()
            {
                ViewModelType = typeof(Viewpoint.Core.ViewModels.UserSettingsViewModel),
            };
            var converter = Mvx.Resolve<MvvmCross.Core.ViewModels.IMvxNavigationSerializer>();
            string param = converter.Serializer.SerializeObject(settingsRequest);
            ContentFrame.Navigate(typeof(UserSettingsView), param);`

**UserSettingView**
`public sealed partial class UserSettingsView : MvxWindowsPage
{
        private ObservableDictionary defaultViewModel = new ObservableDictionary();
        
        public ObservableDictionary DefaultViewModel
        {
            get { return this.defaultViewModel; }
        }

        public new UserSettingsViewModel ViewModel
        {
            get { return (UserSettingsViewModel)base.ViewModel; }
            set { base.ViewModel = value; }
        }

        public UserSettingsView()
        {
            this.InitializeComponent();
        }      
    }`

**Comment by JGKL** [comment]
I faced the same issue after updating from MvvmCross 4 to 6. I fixed it by using `MvxWindowsViewPresenter` it's `string GetRequestText(MvxViewModelRequest request)` to serialize the request for me.

So what I had before was:
` var requestText = converter.Serializer.SerializeObject(new MvxViewModelRequest() { ViewModelType = typeof(MainViewModel) });
_rootFrame.Navigate(typeof(MainView), requestText);`
this resulted in `requestText` having the value: "'Type'='MobielToezicht.Core.Business.ViewModels.MainViewModel';'Params'='';'Pres'=''" and caused the thrown exception in `Navigate`.

After the update I changed it to:
`var requestText = GetRequestText(new MvxViewModelRequest() { ViewModelType = typeof(MainViewModel) });
_rootFrame.Navigate(typeof(MainView), requestText);`
this resulted in  `requestText` having the value: "'MvxLaunchData'='\'Type\'=\'MobielToezicht.Core.Business.ViewModels.MainViewModel\';\'Params\'=\'\';\'Pres\'=\'\''" and didn't cause the thrown exception anymore.
