### ISSUE TITLE
InvalidCastException when getting Viewmodel from MvxAppCompatActivity

### ISSUE THREAD

**Issue by ornolisvt** [MvvmCross/MvvmCross#3018]
## 🐛 Bug Report
I am using Fabric Crashlytics to track errors in an android application. Sometimes the following error occurs, which I have not been able to reproduce:

Fatal Exception: android.runtime.JavaProxyThrowable: System.InvalidCastException: Specified cast is not valid.
  at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
  at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatActivity`1[TViewModel].get_ViewModel () [0x00006] in <d8cdfd295a0b47c1860216b7907c5fb1>:0 
  at PayPhone.Customer.Droid.Views.MainMenu.MainMenuView.SetupTabsWithViewPager () [0x00022] in <2584f3c0a89e4de38795adc32de36085>:0 
  at PayPhone.Customer.Droid.Views.MainMenu.MainMenuView.OnCreate (Android.OS.Bundle bundle) [0x00059] in <2584f3c0a89e4de38795adc32de36085>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <dbf2ba1453d14d3ea5aaac6a9bac4af2>:0 
  at (wrapper dynamic-method) System.Object.59421673-9c8e-4cac-becf-53720680fabd(intptr,intptr,intptr)
       at md52b28ea8eb2071a44e75d6df96fa43363.MainMenuView.n_onCreate(MainMenuView.java)
       at md52b28ea8eb2071a44e75d6df96fa43363.MainMenuView.onCreate(MainMenuView.java:41)
       at android.app.Activity.performCreate(Activity.java:7174)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

One time I had a similar problem with Xamarin when compiling the app in release, I tried to cast an object of type AnimatedVectorDrawable that implements IAnimatable, when casting to IAnimatable I got an invalid cast error, so I had to cast AnimatableVectorDrawable. Maybe this could be a similar behavior.
### Expected behavior
It is expected to build the viewpager without errors and be displayed in a tablayout
### Reproduction steps
The viewpager is built like this:

`_viewPager = FindViewById<ViewPager>(Resource.Id.viewpager);`
`var fragments = new List<MvxViewPagerFragmentInfo>();`
`if (_viewPager == null) return;`
`MvxViewPagerFragmentInfo fragment3 = null;`
`if (ViewModel != null && ViewModel.SelectedTab != 0)`
`	fragment3 = new MvxViewPagerFragmentInfo("3", typeof(Fragment3), typeof(Fragment3ViewModel), new { selectedTab = 1 });`
`else`
`	fragment3 = new MvxViewPagerFragmentInfo("3", typeof(Fragment3), typeof(Fragment3ViewModel));`
`fragments.Add(new MvxViewPagerFragmentInfo("1", typeof(Fragment1), typeof(Fragment1ViewModel)));`
`fragments.Add(new MvxViewPagerFragmentInfo("2", typeof(Fragment2), typeof(Fragment2ViewModel)));`
`fragments.Add(fragment3);`
`_viewPager.Adapter = new MvxCachingFragmentStatePagerAdapter(this, SupportFragmentManager, fragments);`
`_viewPager.AddOnPageChangeListener(this);`
`var tabLayout = FindViewById<TabLayout>(Resource.Id.tabs);`
`tabLayout.SetupWithViewPager(_viewPager);`
### Configuration

**Version:** 5.7.0
Xamarin Android SDK 8.3.0.19
Visual Studio 2017 15.7.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by ornolisvt** [comment]
I forgot the devices where it happened. Excuse me
LG K10 LTE
Galaxy S7 Edge
Huawei Ascend G620S-L03
Xperia Z5 dual
Xiaomi Redmi 5
Huawei Y5 Lite
Galaxy Tab4 7.0
Huawei Y5 II
Galaxy S5 Dual SIM

**Comment by nmilcoff** [comment]
Same issue as: #1305. 

So far none of us was able to reproduce this problem :(. I have several apps using MvvmCross in PRD and have never seen such an error.

@ornolisvt is it possible for you to contribute a minimal reproducible example?

**Comment by nickrandolph** [comment]
Also, please update to latest stable mvvmcross and confirm this is still an issue. If it is, please reproduce the issue using the Playground sample and submit as a PR. This will help us trying to identify the issue

**Comment by ElteHupkes** [comment]
I know how to reproduce this, reliably. #1305 seems to be the original issue but I can't comment on that one, should I put my steps here?

**Comment by Cheesebaron** [comment]
Please create a new issue and reference these two

**Comment by ElteHupkes** [comment]
Alright! Created #3576.

**Comment by ornolisvt** [comment]
Thanks very much @ElteHupkes. This bug has been bothering me for a long time without being able to reproduce successfully

**Comment by ElteHupkes** [comment]
@ornolisvt You're very welcome, I was in the same boat, glad I managed to figure it out :D.
