### ISSUE TITLE
Android XAML Preview no longer works in my Xamarin.Forms project using MvvmCross

### ISSUE THREAD

**Issue by michaelkollmann** [MvvmCross/MvvmCross#3091]
## 🐛 Bug Report

My Android XAML Preview no longer works since implementing MvvmCross in my shared .NET-Standard project. 

Here's the designer error:

```
Failed to process message Load
mono.android.DesignerException: System.NullReferenceException: Object reference not set to an instance of an object
	at mono.android.DesignerException.fromThrowable(DesignerException.java:54)
	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:235)
	at mono.android.DesignerSession.load(DesignerSession.java:314)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:675)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:748)
Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at MvvmCross.Mvx.Resolve[TService] () [0x00006] in <17df0d0bdae848b7a8a12b58d710f763>:0 
  at MvvmCross.Forms.Views.MvxElementExtensions.OnViewAppearing (MvvmCross.Forms.Views.IMvxElement element) [0x0000d] in <f9ca34d669a54607bed0e9bd0795a0d4>:0 
  at MvvmCross.Forms.Views.MvxPageAdapter.HandleAppearingCalled (System.Object sender, System.EventArgs e) [0x00006] in <f9ca34d669a54607bed0e9bd0795a0d4>:0 
  at MvvmCross.Base.MvxDelegateExtensions.Raise (System.EventHandler eventHandler, System.Object sender) [0x00003] in <17df0d0bdae848b7a8a12b58d710f763>:0 
  at MvvmCross.Forms.Views.Base.MvxEventSourceContentPage.OnAppearing () [0x00006] in <f9ca34d669a54607bed0e9bd0795a0d4>:0 
  at MvvmCross.Forms.Views.MvxContentPage.OnAppearing () [0x00000] in <f9ca34d669a54607bed0e9bd0795a0d4>:0 
  at Xamarin.Forms.Page.SendAppearing () [0x00024] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:311 
  at Xamarin.Forms.Platform.Android.PageRenderer.OnAttachedToWindow () [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\PageRenderer.cs:42 
  at Android.Views.View.n_OnAttachedToWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <a10f61e70eeb434e952fef884856c199>:0 
  at (wrapper dynamic-method) System.Object.11(intptr,intptr)
	at md51558244f76c53b6aeda52c8a337f2c37.PageRenderer.n_onAttachedToWindow(Native Method)
	at md51558244f76c53b6aeda52c8a337f2c37.PageRenderer.onAttachedToWindow(PageRenderer.java:55)
	at android.view.View.dispatchAttachedToWindow(View.java:17445)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3326)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:334)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:270)
	at mono.android.DesignerSession.load(DesignerSession.java:307)
	... 4 more

```

### Expected behavior

I'd expect the Android XAML Preview to work just like the iOS XAML Preview does.

### Reproduction steps

I uploaded my solution to https://github.com/michaelkollmann/mvvmcrossissue.git
Just open the solution, go to project "mvvmcrossissue", folder Views and open any of the .xaml-files inside. When trying to preview the Android version the error above is being shown. When previewing iOS everything is fine.
I can reproduce the issue on two different machines so you should also be able, too.

### Configuration

**Visual Studio:** 15.8.3

**Version:** 6.1.2

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by michaelkollmann** [comment]
Thank you very much!

I'm not familiar with your release process. When do you expect I can get an updated NuGet package (either 6.1.2 (3?) or 6.2.0 preview) to work with?

**Comment by nickrandolph** [comment]
@Cheesebaron correct me if I'm wrong but there should be a myget package generated as soon as the PR is merged???

**Comment by Cheesebaron** [comment]
There, should, yes.

**Comment by kharabyasser** [comment]
8 hours search now couldn't find any thing more than 5 issues about this (since 2017) non has been resolved and closed!

**Comment by Cheesebaron** [comment]
@kharabyasser cool story. If you want to do something about, how about fixing it yourself? The code is open source and we are accepting Pull Requests.
