### ISSUE TITLE
Android is crashing if app opens from deep linking

### ISSUE THREAD

**Issue by xyashapyx** [MvvmCross/MvvmCross#3141]
## 🐛 Bug Report

I'm trying to open android version of my app with deep linking but it fails if the app is not started. Meanwhile, IOS version works well.

Here is stack trace of the error:
`android.runtime.JavaProxyThrowable: System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable1[T] source, System.Boolean& found) [0x0000d] in <c71a230fbf1c468a803f281b7366d3b2>:0 
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable1[T] source) [0x00000] in <c71a230fbf1c468a803f281b7366d3b2>:0 
  at MvvmCross.Forms.Platforms.Android.Core.MvxFormsAndroidSetup.get_FormsApplication () [0x00036] in <f9ca34d669a54607bed0e9bd0795a0d4>:0 
  at MvvmCross.Forms.Platforms.Android.Core.MvxFormsAndroidSetup.CreateViewPresenter () [0x00006] in <f9ca34d669a54607bed0e9bd0795a0d4>:0 
  at MvvmCross.Platforms.Android.Core.MvxAndroidSetup.get_Presenter () [0x00000] in <17df0d0bdae848b7a8a12b58d710f763>:0 
  at MvvmCross.Platforms.Android.Core.MvxAndroidSetup.RegisterPresenter () [0x00000] in <17df0d0bdae848b7a8a12b58d710f763>:0 
  at MvvmCross.Platforms.Android.Core.MvxAndroidSetup.InitializePlatformServices () [0x0000c] in <17df0d0bdae848b7a8a12b58d710f763>:0 
  at MvvmCross.Core.MvxSetup.InitializePrimary () [0x00052] in <17df0d0bdae848b7a8a12b58d710f763>:0 
  at MvvmCross.Core.MvxSetupSingleton.StartSetupInitialization () [0x0000a] in <17df0d0bdae848b7a8a12b58d710f763>:0 
  at MvvmCross.Core.MvxSetupSingleton.EnsureInitialized () [0x00017] in <17df0d0bdae848b7a8a12b58d710f763>:0 
  at MvvmCross.Forms.Platforms.Android.Views.MvxFormsAppCompatActivity.OnCreate (Android.OS.Bundle bundle) [0x0000c] in <f9ca34d669a54607bed0e9bd0795a0d4>:0 
  at Littler.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x0003c] in <084513e095944553b693ad664a774f65>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <a10f61e70eeb434e952fef884856c199>:0 
  at (wrapper dynamic-method) System.Object.7(intptr,intptr,intptr)
 at md5e1ed087b366ab69ff4957aecf6c356ce.MainActivity.n_onCreate(Native Method)
 at md5e1ed087b366ab69ff4957aecf6c356ce.MainActivity.onCreate(MainActivity.java:32)
 at android.app.Activity.performCreate(Activity.java:6856)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2807)
 at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:163)
 at android.app.ActivityThread.main(ActivityThread.java:6359)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)`

seems like Bundle is null. 

Here is my OnCreate method

`protectedoverride void OnCreate(Bundle bundle)
 {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;
            base.OnCreate(bundle);
}` 

and my assembly registration under view model [assembly: MvxNavigation(typeof(InfoViewModel), @"myApp://info/\?info=(?<Info>[a-z]*)$")]

### Expected behavior

App will start from even if it was not loaded to memory

### Configuration

**Version:** 6.1.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by SebastianKruseWago** [comment]
And know that this is not helpful but I can confirm at least that deep linking works with 6.1.2 of MVX. I use it myself in two apps and I can use the link to start my app on iOS and Android as well. So while you waiting for an answer you may want to continue the debugging.

**Comment by xyashapyx** [comment]
@SebastianKruseWago, the tricky thing is that I have to debug app starting from the link, so, the debugger is not attached at that moment.

**Comment by vuurbeving** [comment]
I did encounter a similar issue recently. My app crashed when opening from a link, only if the app wasn't running (on Android).

I do think it is a little different from yours (different cause), so I opened a separate issue: #3161

**Comment by nmilcoff** [comment]
Would it be possible for you guys to upload a repro case? That will be super helpful!
