### ISSUE TITLE
MvxCommand NullRef on construction within tests

### ISSUE THREAD

**Issue by projectgoav** [MvvmCross/MvvmCross#3282]
## 🐛 Bug Report

NullReference exception thrown when creating an MvxCommand when IoC is not available. 

The following code throws:
```C#
public class MvxNullRef
{
    public void ThrowNullRef()
    {
        var x = new MvxCommand(() => Console.WriteLine("Hello there!"));
    }
}
```

This code doesn't throw:
```C#
public class MvxNoNullRef : MvxIoCSupportingTest
{
    public void WillNotThrowNullRef()
    {
        base.Setup()
        var x = new MvxCommand(() => Console.WriteLine("Hello there!"));
    }
}
```

ExceptionStack:

```txt
   at MvvmCross.Commands.MvxCommandBase..ctor()
   at MvvmCross.Commands.MvxCommand..ctor(Action execute)
   at My.Test.Code.Method()
```

### Expected behavior
An MvxCommand should be constructed and not rely on IoC

### Configuration

**Version:** 6.2.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by projectgoav** [comment]
Just noticed this has already been fixed here: https://github.com/MvvmCross/MvvmCross/issues/3197

I was only searching for open issues. My bad!
