### ISSUE TITLE
Add Android 28.0.01 support

### ISSUE THREAD

**Issue by beylkhanovdamir** [MvvmCross/MvvmCross#3459]
## 🚀 Feature Requests

XF 3.6.0.539721
The latest MmmVCross 6.3.1 doesn't compatible with Xamarin.Android.* 28.0.01

### Describe the feature
I can't use mvvmCross 6.3.1 with the latest Xamarin.Android.Support.* 28.0.0.1 packages

### Platforms affected (mark all that apply)
- [x] :monkey: Xamarin.Forms
- [x] :robot: Android
- [ ] :iphone: iOS
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS

**Comment by martijn00** [comment]
MvvmCross supports 28.0.0.1 fine. I use it in both my Forms and native projects. Also see: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross.Android.Support/V7.AppCompat/MvvmCross.Droid.Support.V7.AppCompat.csproj#L19

**Comment by beylkhanovdamir** [comment]
@martijn00 

look at stack trace please

Restoring packages for D:\Projects\Omni.App\Omni.App\Omni.App.Android\Omni.App.Android.csproj...
NU1202: Package MvvmCross.Droid.Support.V7.AppCompat 6.3.1 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package MvvmCross.Droid.Support.V7.AppCompat 6.3.1 supports: monoandroid90 (MonoAndroid,Version=v9.0)
Package restore failed. Rolling back package changes for 'Omni.App.Android'.
NuGet.PackageManagement.PackageReferenceRollbackException: Package restore failed. Rolling back package changes for 'Omni.App.Android'.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation.<>c__DisplayClass5_0.<<InstallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation.<InstallInternal>d__8.MoveNext()

@ Installing MvvmCross.Droid.Support.V7.AppCompat in Omni.App.Android finished (0,249 sec)
[Notification][Install] Install failed (project: Omni.App.Android, package: MvvmCross.Droid.Support.V7.AppCompat v6.3.1)
Package restore failed. Rolling back package changes for 'Omni.App.Android'.

**Comment by Cheesebaron** [comment]
@beylkhanovdamir `MonoAndroid,Version=v8.1` you need to target 9.0
