### ISSUE TITLE
Object reference not set to an instance of an object. When add object to MvxObservableCollection

### ISSUE THREAD

**Issue by Nyweron** [MvvmCross/MvvmCross#3571]
Hello,

I want to show you my problem with solution, maybe this will be helpful for others.

**My case:**
```
public MvxObservableCollection<object> SelectedItems
{
	get => _selectedItems;
	set => SetProperty(ref _selectedItems, value);
}
```
```
[Test]
public void ShouldSetSelectedObjects()
{
	// ARRANGE
	var target = CreateFooTarget();
	var fooData = _mock.GetMock<FooData>();

	target.SelectedItems.Add(new ListItemModel()); //Error System.NullReferenceException Message=Object reference not set to an instance of an object.
		
	// ACT
	target.AddCommand.Execute(null);

	// ASSERT
	Assert.AreEqual(1, fooData.SelectedObjects.Count);
}
```

**Error:**
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MvvmCross
  StackTrace:
   at MvvmCross.ViewModels.MvxObservableCollection`1.InvokeOnMainThread(Action action) in C:\projects\mvvmcross\MvvmCross\ViewModels\MvxObservableCollection.cs:line 257
   at MvvmCross.ViewModels.MvxObservableCollection`1.<OnPropertyChanged>d__15.MoveNext() in C:\projects\mvvmcross\MvvmCross\ViewModels\MvxObservableCollection.cs:line 262
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\482\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\482\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 167
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\482\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in E:\A\_work\482\s\src\mscorlib\src\System\Threading\ThreadPool.cs:line 588

```

**Solution:**

```
target.SelectedItems =
	new MvxObservableCollection<object>
	(
		new List<ListItemModel>()
		{
			new ListItemModel()
		}
	);
```
```
[Test]
public void ShouldSetSelectedPresentations()
{
	// ARRANGE
	var target = CreateFooTarget();
	var fooData = _mock.GetMock<FooData>();

	target.SelectedItems =
		new MvxObservableCollection<object>
		(
			new List<ListItemModel>()
			{
				new ListItemModel()
			}
		);
	
	// ACT
	target.AddCommand.Execute(null);

	// ASSERT
	Assert.AreEqual(1, fooData.SelectedObjects.Count);
}
```

PS
I don't sure in which section i should put this, so if it is helpful set This in correct place :)

**Comment by Cheesebaron** [comment]
`MvxObservableCollection` marshalls adding/moving/removal of items to the main thread. This happens through the `InvokeOnMainThread` method inside of it, which in turn uses `MvxMainThreadAsyncDispatcher`. If you haven't registered one of these in your test fixture, it will obviously blow up.

This doesn't really seem like a bug, but rather a hidden dependency that type has, which you haven't fulfilled.
