### ISSUE TITLE
Logged crash in MvxAppCompatViewPresenter.CreateFragment

### ISSUE THREAD

**Issue by SamuelDebruyn** [MvvmCross/MvvmCross#3655]
## 🔙 Regression

Our crash analytics (App Center) detected a crash which looks to be introduced in MvvmCross 6.4.x

My apologies for not adhering to the template as I can't give you any reproduction steps. We have not experienced this crash during development and have no idea when this happens. But it's a significant amount of our userbase (between 3 and 4% - 150+ users) so maybe someone here can spot the cause of this crash or can help with reproduction.

### Android versions

- Android 8.0
- Android 8.1

### Devices

- Samsung Galaxy A6 (phone)
- Samsung Galaxy Tab A 2016 (tablet)

### Stack traces

```
Xamarin Exception Stack:
MvvmCross.Exceptions.MvxException: Cannot create Fragment 'md5f01b142d528e8bd3e4f152995b663372.DialogFragmentForceLogout'. Are you use the wrong base class?
  at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatViewPresenter.CreateFragment (MvvmCross.Presenters.Attributes.MvxBasePresentationAttribute attribute, System.String fragmentName) [0x00032] in <42fdaeba8cd54d4eb367f231df2125d3>:0
  at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatViewPresenter.ShowDialogFragment (System.Type view, MvvmCross.Platforms.Android.Presenters.Attributes.MvxDialogFragmentPresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request) [0x00018] in <42fdaeba8cd54d4eb367f231df2125d3>:0
  at MvvmCross.Presenters.MvxPresentationAttributeExtensions+<>c__DisplayClass4_0`1[TMvxPresentationAttribute].<Register>b__0 (System.Type view, MvvmCross.Presenters.Attributes.IMvxPresentationAttribute attribute, MvvmCross.ViewModels.MvxViewModelRequest request) [0x00000] in <c2171310cfb044f6b5ac8146e37fc672>:0
  at MvvmCross.Presenters.MvxAttributeViewPresenter.Show (MvvmCross.ViewModels.MvxViewModelRequest request) [0x00014] in <c2171310cfb044f6b5ac8146e37fc672>:0
  at MvvmCross.Platforms.Android.Views.MvxAndroidViewDispatcher+<>c__DisplayClass2_0.<ShowViewModel>b__0 () [0x00000] in <c2171310cfb044f6b5ac8146e37fc672>:0
  at MvvmCross.Base.MvxMainThreadAsyncDispatcher+<>c__DisplayClass1_0.<ExecuteOnMainThreadAsync>b__0 () [0x00011] in <c2171310cfb044f6b5ac8146e37fc672>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <714599c65ac34c17bd9e49d680561038>:0
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <96825e2d5d6d4e3d99b7d0aef274d521>:0
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <96825e2d5d6d4e3d99b7d0aef274d521>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <96825e2d5d6d4e3d99b7d0aef274d521>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.47(intptr,intptr)
--- End of inner exception stack trace ---
  Java.Lang.RuntimeException: Attempt to invoke virtual method 'java.lang.ClassLoader android.content.Context.getClassLoader()' on a null object reference
    at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <acedc63e75b942e9831cb17958fb9ab9>:0
    at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <acedc63e75b942e9831cb17958fb9ab9>:0
    at Android.Support.V4.App.Fragment.Instantiate (Android.Content.Context context, System.String fname) [0x0004b] in <a3c57b37330442f08283767bee93a1da>:0
    at MvvmCross.Droid.Support.V7.AppCompat.MvxAppCompatViewPresenter.CreateFragment (MvvmCross.Presenters.Attributes.MvxBasePresentationAttribute attribute, System.String fragmentName) [0x00006] in <42fdaeba8cd54d4eb367f231df2125d3>:0
    at java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader android.content.Context.getClassLoader()' on a null object reference
    at android.support.v4.app.Fragment.instantiate(Fragment.java:440)
    at android.support.v4.app.Fragment.instantiate(Fragment.java:418)
    at mono.java.lang.RunnableImplementor.n_run(Native Method)
    at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Thread 2:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1536)
2   java.lang.Thread.getAllStackTraces(Thread.java:1586)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:970)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:55)
5   mono.java.lang.RunnableImplementor.n_run(RunnableImplementor.java:-2)
6   mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
7   android.os.Handler.handleCallback(Handler.java:789)
8   android.os.Handler.dispatchMessage(Handler.java:98)
9   android.os.Looper.loop(Looper.java:164)
10  android.app.ActivityThread.main(ActivityThread.java:6944)
11  java.lang.reflect.Method.invoke(Method.java:-2)
12  com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
13  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Thread 955790:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
2   java.lang.Daemons$Daemon.run(Daemons.java:103)
3   java.lang.Thread.run(Thread.java:764)

Thread 955791:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
5   java.lang.Daemons$Daemon.run(Daemons.java:103)
6   java.lang.Thread.run(Thread.java:764)

Thread 955792:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:373)
2   java.lang.Thread.sleep(Thread.java:314)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:342)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:364)
5   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:281)
6   java.lang.Daemons$Daemon.run(Daemons.java:103)
7   java.lang.Thread.run(Thread.java:764)

Thread 955807:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 955810:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 955811:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:325)
2   android.os.Looper.loop(Looper.java:142)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 955820:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 955822:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)

Thread 955823:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:101)
2   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
3   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
4   java.lang.Thread.run(Thread.java:764)

Thread 955824:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:323)
2   com.android.okhttp.okio.AsyncTimeout.-wrap0
3   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)

Thread 955825:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2135)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:764)
```

### Configuration

**Version:** 6.4.x (we upgraded from 6.3.1 to 6.4.1 and skipped 6.4.0)

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
And what type is `DialogFragmentForceLogout`?

**Comment by SamuelDebruyn** [comment]
@Cheesebaron `MvxDialogFragment<ForceLogoutViewModel>` so it inherits `IMvxFragmentView`

This is its source:

```
	[MvxDialogFragmentPresentation(Cancelable = false, AddToBackStack = false)]
	public class DialogFragmentForceLogout : MvxDialogFragment<ForceLogoutViewModel>
	{
		public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
		{
			base.OnCreateView(inflater, container, savedInstanceState);
			return this.BindingInflate(Resource.Layout.dialog_force_logout, null);
		}

		public override void OnResume()
		{
			base.OnResume();

			var width = (int)TypedValue.ApplyDimension(ComplexUnitType.Dip, SharedConstants.LayoutConstants.DEFAULT_POPUP_WIDTH,
				Resources.DisplayMetrics);

			if (width > Resources.DisplayMetrics.WidthPixels)
			{
				width = Resources.DisplayMetrics.WidthPixels;
			}

			Dialog.Window.SetLayout(width, ConstraintLayout.LayoutParams.WrapContent);
		}
	}
```

Thanks for looking into this. Couldn't find what's null.

**Comment by Cheesebaron** [comment]
I am pretty sure this is due to the App being in the background and this dialog is trying to show. As is right now this will make CurrentActivity null.

You can try to repro it by wrapping your call that navigates to this dialog, in a Task.Run that delays the call. While it is delaying it you press home so the App goes into the background. So give it enough delay for you to do this.

You should see a similar crash then.
