### ISSUE TITLE
Exception Java.Lang.NoSuchMethodError: no method with name='isDestroyed' occurs on API 16

### ISSUE THREAD

**Issue by hubocan** [MvvmCross/MvvmCross#3727]
## 🐛 Bug Report

When I rotate the screen of device **with API 16** and MvxAppCompatActivity is recreated, the exception Java.Lang.NoSuchMethodError is thrown. Exception occurs in MvxAppCompatActivity.OnDestroy().

Stack trace:

```
Java.Lang.NoSuchMethodError: no method with name='isDestroyed' signature='()Z' in class Landroid/support/v7/app/AppCompatActivity;
  at Company.Android.Product.AppPlatform.OnUnhandledException (System.Object sender, Android.Runtime.RaiseThrowableEventArgs e) [0x00017] in C:\Users\Username\Source\Workspaces\Product\Android\Product.Droid\AppPlatform.cs:245 
  at Android.Runtime.AndroidEnvironment.UnhandledException (System.Exception e) [0x0003e] in <4a189ea3b82b48a089ac9002b2abc206>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr)
  at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr)
  --- End of managed Java.Lang.NoSuchMethodError stack trace ---
java.lang.NoSuchMethodError: no method with name='isDestroyed' signature='()Z' in class Landroid/support/v7/app/AppCompatActivity;
	at mvvmcross.droid.support.v7.appcompat.MvxAppCompatActivity.n_onDestroy(Native Method)
	at mvvmcross.droid.support.v7.appcompat.MvxAppCompatActivity.onDestroy(MvxAppCompatActivity.java:61)
	at android.app.Activity.performDestroy(Activity.java:5327)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1124)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3298)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3329)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3527)
	at android.app.ActivityThread.access$700(ActivityThread.java:140)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4895)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
	at dalvik.system.NativeStart.main(Native Method)
```

### Expected behavior

Should not throw an exception.

### Reproduction steps

1. Start application with MvxAppCompatActivity on device with API 16.
2. Rotate screen to recreate activity.

### Configuration

**Version:** 6.4.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
As a workaround, can you try override `OnDestroy` in your own activity and try not calling the base?

**Comment by hubocan** [comment]
I have already tried it and then it throws: Android.Util.AndroidRuntimeException
Activity {HomeView} did not call through to super.onDestroy()

Please check it out, as it can be some easy one to fix. (It looks like there is call for non-existent method in API 16.) We have a lot of Android devices with API 16 and it will be a show stopper.

**Comment by Cheesebaron** [comment]
https://github.com/MvvmCross/MvvmCross/blob/6.4.2/MvvmCross.Android.Support/V7.AppCompat/MvxAppCompatActivity.cs#L95

We don't call `IsDestroyed`, we do however call `IsFinishing` which is something that has been supported since API level 1.

The stack trace might be a bit misleading. The only place we check for `IsDestroyed` is through this call: https://github.com/MvvmCross/MvvmCross/blob/6.4.2/MvvmCross/Platforms/Android/Views/MvxApplicationCallbacksCurrentTopActivity.cs#L92

**Comment by hubocan** [comment]
If I call IsDestroyed, MvxAppCompatActivity will crash with the same exception on API 16. IsDestroyed is available in API 17+.

**Comment by hubocan** [comment]
Right now, I have finished the update from MVVMCross 6.4.2 to the latest 8.0.2 and this bug still occurs (or again). Can you check if the fix is still applied, please?

**Comment by hubocan** [comment]
So, I've checked it myself and it is definitely a regression from 8.0 (7.0-7.1 was fine). Please fix it and release ASAP.

**Comment by Cheesebaron** [comment]
Yes, it was done in #3872.

Won't fix. You can always stick to an older version and come back complaining when that breaks 😄
