### ISSUE TITLE
Color plugin breaks WPF designer with NullReferenceException

### ISSUE THREAD

**Issue by snechaev** [MvvmCross/MvvmCross#4144]
## 🐛 Bug Report

When using Color plugin with WPF, I got NullReferenceException in WPF designer.
Stack
```
   at MvvmCross.Plugin.Color.MvxColorValueConverter.get_NativeColor()
   at MvvmCross.Plugin.Color.MvxColorValueConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at MvvmCross.Platforms.Wpf.Converters.MvxNativeValueConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at TipCalc.WPF.Converters.NativeColorConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
```

This looks like the WPF-specific version of  #323 or #357. This is also looks like that for WPF it is never worked, so I posting bug, not regress.

The problem could not be solved as suggested in documentation by adding
`<color:MvxColorDesignTimeHelper x:Key="DesignTimeColor"/>`
 (this does not compile for WPF)

### Expected behavior
WPF designer works fine, including preview.

### Reproduction steps
* Open solution [TipCalc.zip](https://github.com/MvvmCross/MvvmCross/files/6233944/TipCalc.zip). This is just a TipCalc sample with following changes
    * `TestColor` property added in `TipViewModel`
    * `NativeColorConverter` added in WPF project
    * `TestColor` referenced in `TipView` with `NativeColorConverter` converter.
* Build
* Open `TipView.xaml` and check preview - it shows error.
* If the `Background` attribute, which referencing `NativeColor` converter, will be removed from the xaml, designer will work again. And it will continue working even if I put color with converter back. But it is brokes again after VS relaunch or project unload/reload.

### Possible workaround
All works, if add `MvxDesignTimeChecker.Check();` in `NativeColorConverter.Convert` before calling `base.Convert`

### Configuration

**Version:** 7.1.2
VS 2019 Pro 16.9.3

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by snechaev** [comment]
There is the same problem with the MvxInvertedVisibilityValueConverter, but the workaround with `MvxDesignTimeChecker.Check();` does not helped here. Don't know if I need to post a separate issue for this or not as it looks very similar to the current one.

**Comment by Cheesebaron** [comment]
Looks like the same issue. No need for a separate issue for this :)
