### ISSUE TITLE
Upgrade to 8.0.2 throws System.ReferenceNullException for Bind

### ISSUE THREAD

**Issue by naveenbuziness** [MvvmCross/MvvmCross#4348]
## 🔙 Regression

Upgrade to 8.0.2 throws System.ReferenceNullException on use of CreateBindingSet and call bind
Note:- We have migrated from .Net5 to .Net6
### Old (and correct) behavior
App starts up normally
### Current behavior
Throws System.ReferenceNullException "Object reference not set to an instance of object" for setting bind after CreatBindingSet()
### Reproduction steps
Create binding set and call bind.
![Exception](https://user-images.githubusercontent.com/94976580/146652014-a2018633-0ff7-4862-876a-ede016ed3a8f.PNG)

Stack Trace
  at MvvmCross.Binding.BindingContext.MvxBaseFluentBindingDescription`1.TargetPropertyName(Expression`1 targetPropertyPath)
   at MvvmCross.Binding.BindingContext.MvxFluentBindingDescription`2.For(Expression`1 targetPropertyPath)
   at DNA.Scheduler.WinUI.Gantt.GanttView..ctor() in D:\Naveen\Source\Repos\DNA.Central\DNA.Scheduler\DNA.Scheduler.WinUI\Gantt\GanttView.xaml.cs:line 31
### Configuration

**Version:** 6.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by Cheesebaron** [comment]
I wouldn't call this a regression, just unsupported platform for now.

We do have a WinUI PR open, which might solve your issue. We also have another PR with .NET 6 support, which I need to finish up.

So won't do anything about this binding error you get until those get in. You could instead just use regular XAML bindings or whatever WPF/WinUI provides.

**Comment by revred** [comment]
This is also the issue that I have run into. Is there a timeframe to merge this into the main trunk or is there a way forward for the interim?
