### ISSUE TITLE
MvvmCross 9.0.2 throws InvalidOperationException when calling MvxSetupSingleton.EnsureInitialized()

### ISSUE THREAD

**Issue by pwojtysiak** [MvvmCross/MvvmCross#4532]
## 🔙 Regression

After upgrading to version 9.0.2 the app throws `System.InvalidOperationException: Cannot create Views Container without ApplicationContext` when calling `MvvmCross.Core.MvxSetupSingleton.EnsureInitialized()` and the app is killed. I used this method when receiving notifications in FirebaseMessagingService. It crashes because there is no activity ([_currentTopActivity?.Activity?.ApplicationContext](https://github.com/MvvmCross/MvvmCross/blob/8457be7d0871e65c5efc785ad149fc0421d6cfe2/MvvmCross/Platforms/Android/Core/MvxAndroidSetup.cs#L55) is null). 

### Old (and correct) behavior
The method  MvxSetupSingleton.EnsureInitialized doesn't crash. 

### Current behavior
When the background service (like FirebaseMessagingService) calls:
```
var setup = MvxAndroidSetupSingleton.EnsureSingletonAvailable(ApplicationContext);
setup.EnsureInitialized(); 
```
then it throws 
```
android.runtime.JavaProxyThrowable: System.InvalidOperationException: Cannot create Views Container without ApplicationContext
13:06:30.292  I     at MvvmCross.Platforms.Android.Core.MvxAndroidSetup.CreateViewsContainer(IMvxIoCProvider iocProvider)
13:06:30.292  I     at MvvmCross.Core.MvxSetup.InitializeViewsContainer(IMvxIoCProvider iocProvider)
13:06:30.292  I     at MvvmCross.Core.MvxSetup.InitializeSecondary()
13:06:30.292  I     at MvvmCross.Core.MvxSetupSingleton.<StartSetupInitialization>b__13_0()
13:06:30.292  I     at MvvmCross.Core.MvxSetupSingleton.EnsureInitialized()
13:06:30.292  I     at MvvmCross.Platforms.Android.Services.MvxIntentService.OnHandleIntent(Intent intent)
13:06:30.292  I     at MyXamarinApp.Droid.CustomIntentService.OnHandleIntent(Intent intent)
13:06:30.292  I     at Android.App.IntentService.n_OnHandleIntent_Landroid_content_Intent_(IntPtr jnienv, IntPtr native__this, IntPtr native_intent)
13:06:30.292  I     at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
13:06:30.292  I  	at com.mvxscaffolding.app.CustomIntentService.n_onHandleIntent(Native Method)
13:06:30.292  I  	at com.mvxscaffolding.app.CustomIntentService.onHandleIntent(CustomIntentService.java:37)
13:06:30.292  I  	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
13:06:30.292  I  	at android.os.Handler.dispatchMessage(Handler.java:106)
13:06:30.292  I  	at android.os.Looper.loopOnce(Looper.java:201)
13:06:30.292  I  	at android.os.Looper.loop(Looper.java:288)
13:06:30.292  I  	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Reproduction steps
1. Run MyXamarinApp
2. Kill the app
3. Start the service `CustomIntentService` from the terminal: `./adb shell am start-foreground-service com.mvxscaffolding.app/.CustomIntentService`
4. setup.EnsureInitialized throws `InvalidOperationException: Cannot create Views Container without ApplicationContext`

Sample Source Code：
[MyXamarinApp.zip](https://github.com/MvvmCross/MvvmCross/files/10324731/MyXamarinApp.zip)

### Configuration

net6.0-android
**Version:**  MvvmCross 9.0.2

**Platform:** 
- [x] :robot: Android

**Comment by Cheesebaron** [comment]
Thanks for reporting this.

I will have a look at fixing this. I saw something similar with MvxFragment. This is some old code I would really like to have a good look at and change.

EnsureInitialized, should ideally only happen on App startup and not at a random point in the App lifecycle.

For now I will patch this one, but will make a proper fix for a future version of MvvmCross.
