### ISSUE TITLE
.NET 8 Android Failed to resolve type MvvmCross.Binding.BindingContext.IMvxBindingContextStack when calling MvxActivity.SetContentView

### ISSUE THREAD

**Issue by snydesc** [MvvmCross/MvvmCross#4780]
## 🐛 Bug Report
When using 9.2.0-beta.4 the following exception is now thrown when calling MvxActivity.SetContentView in OnCreate.
This does not happen when using 9.2.0-beta.2.  I have not tried this in 9.2.0-beta.3.

```
[ERROR] FATAL UNHANDLED EXCEPTION: MvvmCross.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.Binding.BindingContext.IMvxBindingContextStack`1[[MvvmCross.Platforms.Android.Binding.BindingContext.IMvxAndroidBindingContext, MvvmCross, Version=9.2.0.0, Culture=neutral, PublicKeyToken=null]]
[mono-rt]    at MvvmCross.IoC.MvxIoCContainer.Resolve(Type type) in /_/MvvmCross/IoC/MvxIoCContainer.cs:line 256
[mono-rt]    at MvvmCross.IoC.MvxIoCContainer.Resolve[IMvxBindingContextStack`1]() in /_/MvvmCross/IoC/MvxIoCContainer.cs:line 247
[mono-rt]    at MvvmCross.IoC.MvxIoCProvider.Resolve[IMvxBindingContextStack`1]() in /_/MvvmCross/IoC/MvxIoCProvider.cs:line 64
[mono-rt]    at MvvmCross.Binding.BindingContext.MvxBindingContextStackRegistration`1[[MvvmCross.Platforms.Android.Binding.BindingContext.IMvxAndroidBindingContext, MvvmCross, Version=9.2.0.0, Culture=neutral, PublicKeyToken=null]].get_Stack() in /_/MvvmCross/Binding/BindingContext/MvxBindingContextStackRegistration.cs:line 14
[mono-rt]    at MvvmCross.Binding.BindingContext.MvxBindingContextStackRegistration`1[[MvvmCross.Platforms.Android.Binding.BindingContext.IMvxAndroidBindingContext, MvvmCross, Version=9.2.0.0, Culture=neutral, PublicKeyToken=null]]..ctor(IMvxAndroidBindingContext toRegister) in /_/MvvmCross/Binding/BindingContext/MvxBindingContextStackRegistration.cs:line 18
[mono-rt]    at MvvmCross.Platforms.Android.Binding.BindingContext.MvxAndroidBindingContext.CommonInflate(Int32 resourceId, ViewGroup viewGroup, Boolean attachToParent) in /_/MvvmCross/Platforms/Android/Binding/BindingContext/MvxAndroidBindingContext.cs:line 46
[mono-rt]    at MvvmCross.Platforms.Android.Binding.BindingContext.MvxAndroidBindingContext.BindingInflate(Int32 resourceId, ViewGroup viewGroup, Boolean attachToParent) in /_/MvvmCross/Platforms/Android/Binding/BindingContext/MvxAndroidBindingContext.cs:line 37
[mono-rt]    at MvvmCross.Platforms.Android.Binding.BindingContext.MvxAndroidBindingContext.BindingInflate(Int32 resourceId, ViewGroup viewGroup) in /_/MvvmCross/Platforms/Android/Binding/BindingContext/MvxAndroidBindingContext.cs:line 32
[mono-rt]    at MvvmCross.Platforms.Android.Binding.BindingContext.MvxBindingContextOwnerExtensions.BindingInflate(IMvxBindingContextOwner owner, Int32 resourceId, ViewGroup viewGroup) in /_/MvvmCross/Platforms/Android/Binding/BindingContext/MvxBindingContextOwnerExtensions.cs:line 15
[mono-rt]    at MvvmCross.Platforms.Android.Views.MvxActivity.SetContentView(Int32 layoutResID) in /_/MvvmCross/Platforms/Android/Views/MvxActivity.cs:line 64
[mono-rt]    at XXXXXXXXXX.MainView.OnCreate(Bundle savedInstanceState) in C:\XXXXXXXX\MainView.cs:line 53
[mono-rt]    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Activity.cs:line 3082
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 125
```

### Expected behavior
No exception should be thrown

### Reproduction steps
Call SetContentView in the OnCreate function located in the activity that inherits from MvxActivity

### Configuration

**Version:** 9.2.0-beta.4, .NET 8.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by snydesc** [comment]
I did test with 9.2.0-beta.3 and it also occurs in 9.2.0-beta.3.

Looking at the change history I narrowed it down to the changes made to the plugin code.

If I override InitializeApp in setup.cs to the following then the exception is not thrown:

```
protected override void InitializeApp(IMvxApplication app)
{
   var pluginManager = InitializePluginFramework(Mvx.IoCProvider);
   app.LoadPlugins(pluginManager);
   base.InitializeApp(app);
}
```

My LoadPlugins Looks like this:

```
public override void LoadPlugins(IMvxPluginManager pluginManager)
{   
   base.LoadPlugins(pluginManager);
   pluginManager.EnsurePluginLoaded<MvvmCross.Plugin.Messenger.Plugin>();
   pluginManager.EnsurePluginLoaded<MvvmCross.Plugin.Visibility.Platforms.Android.Plugin>();
   pluginManager.EnsurePluginLoaded<MvvmCross.Plugin.Color.Platforms.Android.Plugin>();
}
```

Commenting out the 3 calls to EnsurePluginLoaded even with the change to InitializeApp will cause the Exception to return.

**Comment by Cheesebaron** [comment]
None of the plugins you are loading are necessary for bindings to work.

Are you overriding `InitializeBindingBuilder` in your Setup.cs file by any chance?

**Comment by snydesc** [comment]
I am not overriding `InitializeBindingBuilder ` or `CreateBindingBuilder `
I did some more digging and was able to remove the calls to EnsurePluginLoaded for the Visibility and Color plugins.

So the following setup to not get the exception is:
```
protected override void InitializeApp(IMvxApplication app)
{
   var pluginManager = InitializePluginFramework(Mvx.IoCProvider);
   app.LoadPlugins(pluginManager);
   base.InitializeApp(app);
}

public override void LoadPlugins(IMvxPluginManager pluginManager)
{   
   base.LoadPlugins(pluginManager);
   pluginManager.EnsurePluginLoaded<MvvmCross.Plugin.Messenger.Plugin>();
}
```

My MainActivity's ViewModel does use dependency injected Services which use IMvxMessenger (injected into the service's constructor).  With the recent change moving the plugin initialization after the call to initialize app could that be causing this issue?  I would have expected an IOC resolve exception if that was the case.

**Comment by Cheesebaron** [comment]
Yes, the order of loading has changed, due to preparation for a different IoC container, and removal of callbacks when certain things get registered in the container.

The Messenger plug-in doesn't need anything else to function, so it _should_ work if registered earlier.

Let me check if maybe App start can be ordered differently too. I get that you want to be able to use dependencies in there to determine which VM to navigate to etc.
