### ISSUE TITLE
[Bug]: Crash after upgrading 8.0 to 9.2.0 inside MvxStartActivity

### ISSUE THREAD

**Issue by projectgoav** [MvvmCross/MvvmCross#4876]
### Description

I upgraded from 8.0.2 to 9.2.0. Changed my MvxSplashScreenActivity to MvxStartActivity
Launch the app, crashes on startup

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]    at MvvmCross.Platforms.Android.Views.MvxActivityViewExtensions.OnLifetimeEvent(IMvxAndroidView androidView, Action`2 report) in /_/MvvmCross/Platforms/Android/Views/MvxActivityViewExtensions.cs:line 126
[mono-rt]    at MvvmCross.Platforms.Android.Views.MvxActivityViewExtensions.OnViewCreate(IMvxAndroidView androidView, Bundle bundle) in /_/MvvmCross/Platforms/Android/Views/MvxActivityViewExtensions.cs:line 36
[mono-rt]    at MvvmCross.Platforms.Android.Views.MvxActivityAdapter.EventSourceOnCreateCalled(Object sender, MvxValueEventArgs`1 eventArgs) in /_/MvvmCross/Platforms/Android/Views/MvxActivityAdapter.cs:line 77
[mono-rt]    at MvvmCross.Base.MvxDelegateExtensions.Raise[Bundle](EventHandler`1 eventHandler, Object sender, Bundle value) in /_/MvvmCross/Base/MvxDelegateExtensions.cs:line 21
[mono-rt]    at MvvmCross.Platforms.Android.Views.Base.MvxEventSourceActivity.OnCreate(Bundle savedInstanceState) in /_/MvvmCross/Platforms/Android/Views/Base/MvxEventSourceActivity.cs:line 29
[mono-rt]    at MvvmCross.Platforms.Android.Views.MvxActivity.OnCreate(Bundle savedInstanceState) in /_/MvvmCross/Platforms/Android/Views/MvxActivity.cs:line 92
[mono-rt]    at MvvmCross.Platforms.Android.Views.MvxStartActivity.OnCreate(Bundle savedInstanceState) in /_/MvvmCross/Platforms/Android/Views/MvxStartActivity.cs:line 49
[mono-rt]    at linnapp.SplashScreen.OnCreate(Bundle savedInstanceState) in Z:\Code\Linn\UI\linnapp.Android\src\linnapp.Android\SplashScreen.cs:line 18
[mono-rt]    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Activity.cs:line 3082
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
```

Is this something known / have we missing something as part of the upgrade path from v8 -> 9?

### Steps to Reproduce

Launch our app.... Crash instantly

### Version with bug

9.2.0

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.0

### Affected platforms

Android

**Comment by projectgoav** [comment]
Occurs on both physical devices and the Android emulator.

**Comment by Cheesebaron** [comment]
I would need more information to help.

Did you create a `MainApplication` class like this:

```csharp
public class MainApplication(IntPtr handle, JniHandleOwnership transfer)
    : MvxAndroidApplication<Setup<PhoneApp>, PhoneApp>(handle, transfer)
```

Is your `Setup` defined something like this:

```csharp
public class Setup<TApplication> :
    MvxAndroidSetup<TApplication> where TApplication : class, IMvxApplication, new()
```

or

```csharp
public class Setup : MvxAndroidSetup<App>
```

**Comment by projectgoav** [comment]
We don't have a `MainApplication` class that inherits from `MvxAndroidApplication`. Instead it's a plain `Android.App.Application`

As for the setup, we use the non-generic version: `class Setup : MvxAndroidSetup`

**Comment by Cheesebaron** [comment]
You need a `MvxAndroidApplication` this is where MvvmCross hooks into Activity lifecycle, which is probably why you are getting a null ref.

**Comment by projectgoav** [comment]
That's the thing I was missing! Thanks very much.

Strange that it all worked before the upgrade. However, we're up and running again :)

**Comment by AndrewStephens-teladoc** [comment]
> That's the thing I was missing! Thanks very much.
> 
> Strange that it all worked before the upgrade. However, we're up and running again :)

I had a similar issue I when needed to upgrade from 9.0.4 to 9.4.0. For some reason it was not set up correctly. When I set it up correctly it started working agin 
```
public class MainApplication(IntPtr handle, JniHandleOwnership transfer)
    : MvxAndroidApplication<Setup<PhoneApp>, PhoneApp>(handle, transfer)
```
