### ISSUE TITLE
MvvmCross not working with Htmlagilitypack

### ISSUE THREAD

**Issue by sta197** [MvvmCross/MvvmCross#805]
Hello.
I would just add the package to Core project. And write this code
HtmlDocument doc = new HtmlDocument();

When the application starts , I get the error navigation.

mvx:Warning:  1,08 ReflectionTypeLoadException masked during loading of xx.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null - error ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
       at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Cirrious.CrossCore.ReflectionExtensions.GetTypes(Assembly assembly)
   at Cirrious.CrossCore.IoC.MvxTypeExtensions.ExceptionSafeGetTypes(Assembly assembly)
mvx:Diagnostic:  1,11 Setup: ViewModelTypeFinder start
mvx:Warning:  1,31 ReflectionTypeLoadException masked during loading of xx.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null - error ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
       at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Cirrious.CrossCore.ReflectionExtensions.GetTypes(Assembly assembly)
   at Cirrious.CrossCore.IoC.MvxTypeExtensions.ExceptionSafeGetTypes(Assembly assembly)
mvx:Diagnostic:  1,33 Setup: ViewsContainer start
mvx:Diagnostic:  1,36 Setup: ViewDispatcher start
mvx:Diagnostic:  1,38 Setup: Views start
mvx:Diagnostic:  1,49 No view model association found for candidate view MainView
mvx:Diagnostic:  1,51 No view model association found for candidate view SettingsView
mvx:Diagnostic:  1,54 No view model association found for candidate view StartView
mvx:Diagnostic:  1,55 Setup: CommandCollectionBuilder start
mvx:Diagnostic:  1,57 Setup: NavigationSerializer start
mvx:Diagnostic:  1,59 Setup: InpcInterception start
mvx:Diagnostic:  1,60 Setup: LastChance start
mvx:Diagnostic:  1,62 Setup: Secondary end
'TaskHost.exe' (CoreCLR: Silverlight AppDomain): Loaded 'C:\windows\system32\WinMetadata\Windows.winmd'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
mvx:Diagnostic:  1,77 Showing ViewModel StartViewModel
mvx:Diagnostic:  2,07 Error seen during navigation request to StartViewModel - error KeyNotFoundException: Could not find view for xx.Core.ViewModels.StartViewModel
       at Cirrious.MvvmCross.Views.MvxViewsContainer.GetViewType(Type viewModelType)
   at Cirrious.MvvmCross.WindowsPhone.Views.MvxPhoneViewsContainer.GetXamlUriFor(MvxViewModelRequest request)
   at Cirrious.MvvmCross.WindowsPhone.Views.MvxPhoneViewPresenter.Show(MvxViewModelRequest request)

If delete code (HtmlDocument doc = new HtmlDocument();), then all is Ok.

P.S. I created Windows Phone 8.0 (Silverlight) project.

**Comment by Uddhao** [comment]
Hi, @sta197 also getting same error. Can you explain how you solved it ?
