### ISSUE TITLE
could not load plugin assembly for type Cirrious.MvvmCross.Plugins.WebBrowser.PluginLoader

### ISSUE THREAD

**Issue by gregberns** [MvvmCross/MvvmCross#872]
I just started using MVX, so hopefully I've provided enough to reproduce.

Summary:
Create a new solution with Ninja and select Json and WebBrowser plugins. When the WPF app is run, there will be an exception thrown in: WPF > App.xaml.cs > DoSetup > setup.initialize()

Note:
If only the WebBrowser plugin is added, this error doesn't occur.

Steps:
1. Open VS2013 (so no projects/solutions should be open)
2. Make sure Ninja coder plugin is installed using 3.2.0
3. Go to Tools > Ninja Coder... > Add Projects
4. On 'Build Options' screen, click Next
5. On Framework, click next
6. On Project Details, add project name 'MvxTest', click Next
7. On View Models, click Next
8. On Plugins, select 'Json' and 'WebBrowser'
9. On Nuget, select 'Newtonsoft Json'
10. Click Finish
11. Let everything get created
12. Set "MvxTest.WPF" as startup project
13. Start WPF project

Error:
An unhandled exception of type 'Cirrious.CrossCore.Exceptions.MvxException' occurred in Cirrious.CrossCore.dll
Additional information: could not load plugin assembly for type Cirrious.MvvmCross.Plugins.WebBrowser.PluginLoader

   at Cirrious.CrossCore.Plugins.MvxFilePluginManager.LoadAssembly(Type toLoad)
   at Cirrious.CrossCore.Plugins.MvxFilePluginManager.FindPlugin(Type toLoad)
   at Cirrious.CrossCore.Plugins.MvxPluginManager.ExceptionWrappedLoadPlugin(Type toLoad)
   at Cirrious.CrossCore.Plugins.MvxPluginManager.EnsurePlatformAdaptionLoaded[T]()
   at Cirrious.MvvmCross.Plugins.WebBrowser.PluginLoader.EnsureLoaded()
   at Cirrious.CrossCore.Plugins.MvxPluginManager.EnsurePluginLoaded(IMvxPluginLoader pluginLoader)
   at Cirrious.CrossCore.Plugins.MvxPluginManager.EnsurePluginLoaded(Type type)
   at Cirrious.CrossCore.Plugins.MvxPluginManager.EnsurePluginLoaded[TType]()
   at Cirrious.CrossCore.Plugins.MvxPluginBootstrapAction`1.Load(IMvxPluginManager manager)
   at Cirrious.CrossCore.Plugins.MvxPluginBootstrapAction`1.RunAction()
   at Cirrious.CrossCore.IoC.MvxSimpleIoCContainer.InternalSetResolver(Type tInterface, IResolver resolver)
   at Cirrious.CrossCore.IoC.MvxSimpleIoCContainer.RegisterSingleton(Type tInterface, Object theObject)
   at Cirrious.CrossCore.IoC.MvxSimpleIoCContainer.RegisterSingleton[TInterface](TInterface theObject)
   at Cirrious.CrossCore.Mvx.RegisterSingleton[TInterface](TInterface service)
   at Cirrious.MvvmCross.Platform.MvxSetup.InitializePluginFramework()
   at Cirrious.MvvmCross.Platform.MvxSetup.InitializeSecondary()
   at Cirrious.MvvmCross.Platform.MvxSetup.Initialize()
   at MvxTest.Wpf.App.DoSetup() in c:\DEVn\MvxTest\MvxTest.Wpf\App.xaml.cs:line 32
   at MvxTest.Wpf.App.OnActivated(EventArgs e) in c:\DEVn\MvxTest\MvxTest.Wpf\App.xaml.cs:line 48
   at System.Windows.Application.WmActivateApp(Int32 wParam)
   at System.Windows.Application.AppFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by Cheesebaron** [comment]
Questions go on StackOverflow in the mvvmcross tag. GitHub is for bug reports and I don't believe your post describes a bug.

If you find out that it is an actual bug, please reopen this issue and well take it from there.

**Comment by slodge** [comment]
It also sounds like this is maybe just an issue with the Ninja plugin - so I'll ping @asudbury about it https://github.com/asudbury/NinjaCoderForMvvmCross 

*ping* ;)

**Comment by gregberns** [comment]
I removed the WebBrowser and re-added it and the same thing occurs. If I cment out the bootstrapper, the issue goes away. 
I've also added the Json and Network plugins, but those work fine.

**Comment by JanZeman** [comment]
As I understand it this plugin does not exist for WPF at all. It has nothing to do with Ninja. At least my attempt to add it to Droid projects adds the reference to files Cirrious.MvvmCross.Plugins.WebBrowser.dll and Cirrious.MvvmCross.Plugins.WebBrowser.Droid.dll but if I do the same it adds only Cirrious.MvvmCross.Plugins.WebBrowser. That lead me to the conclusion that Cirrious.MvvmCross.Plugins.WebBrowser.Wpf does not exist at all and the table I found here (http://www.buildinsider.net/mobile/xamarintips/0053) confirms that. Please correct me if I am wrong.

BR
Jan
